### ISSUE TITLE
capital S not working in visual mode

### ISSUE THREAD

**Issue by brunobmello25** [ggandor/leap.nvim#100]
Steps to reproduce:

- Enter visual mode or visual line mode
- press `S`
- Try pressing two keys to begin search
- note that it will have a strange behavior instead of initiating search (sometimes add a new line above, sometimes deletes current line)

x and capital X both work normally in this visual case but I would like to use s and S for both normal and visual modes

**Comment by ggandor** [comment]
Cannot reproduce. Check what is mapped to `S` with `:xmap S`.

**Comment by brunobmello25** [comment]
apologies, I checked with `:Telescope keymaps` and it said that S was mapped to leap but when checking with xmap I saw that it was actually mapped to nvim-surround. I fixed it here

Thanks!
