### ISSUE TITLE
Composite Unicode characters in the buffer break stuff

### ISSUE THREAD

**Issue by adriancmiranda** [ggandor/leap.nvim#108]
When I press "t" followed by "s" I get this error:
![image](https://user-images.githubusercontent.com/5431310/219438748-3767ffeb-01f4-4097-a005-90ffafa9f178.png)

https://user-images.githubusercontent.com/5431310/219542564-6ca5ce75-9b99-4172-9672-4dae2a92ff6a.mp4

I'm not sure why, any other letter seems fine, but, that's my config (using [Packer](https://github.com/wbthomason/packer.nvim)):

```lua
use({
	disable = false,
	requires = 'https://github.com/tpope/vim-repeat',
	'https://github.com/ggandor/leap.nvim',
	commit = 'a2e57b7',
	config = function()
		local leap = require('leap')
		leap.add_default_mappings()
	end,
})
```

```
NVIM v0.9.0-dev
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
```

Is there any misconfiguration on my part?

**Comment by ggandor** [comment]
The config seems okay. It would be helpful if you could reproduce the error and copy the buffer content with the cursor position marked (it's certainly not the letter combination "ts" that has this evil effect on Leap).

**Comment by ggandor** [comment]
I see you edited the post, but I cannot comprehend anything from a video like this, please include a reproducible example, like:
```
-- type `saz` at the given position

foo [cursor here]bar baz
foo bar baz
```

**Comment by adriancmiranda** [comment]
That's the video that I recorded before, I'm trying to reproduce it again. Probably is related to a conflict with [`quick-scope`](https://github.com/unblevable/quick-scope), but, I have not sure yet. Because of that, I don't reply to you before.

**Comment by ggandor** [comment]
Well, the error is thrown by Leap, so we should keep this open. Just to orient you, the error is about Leap trying to put the label on an invalid column, most probably after EOL.

**Comment by adriancmiranda** [comment]
Yes, and no, it's ok with and without  quick-scope, it was just suspicious but I tried, with no change
Does it have to do with the file size? The file has 136 lines. I'll try after the lunch

**Comment by ggandor** [comment]
> I had to test it before, and yes, it's the emojis, man

Yep, I suspect this is about unicode/multibyte chars then.

**Comment by adriancmiranda** [comment]
Yeah, sure! But, may you reproduce the error with [this file here](https://gist.github.com/adriancmiranda/21a9ae5e5e478cd65cc9582464ffad4e)? or it's only here?

**Comment by ggandor** [comment]
Minimal example to reproduce:
```
  xy ℹ️  xy xy
```
The "xy"s after the fancy "i" will not be found at all. `vim.fn.search` itself finds them alright, the problem is here:

https://github.com/ggandor/leap.nvim/blob/9a69febb2e5a4f5f5a55dd2d7173098fde917bc5/fnl/leap/util.fnl#L30-L38

`strgetchar` fails to extract the proper character in the above case. Most probably this is related to ℹ️ being more than 4 bytes (composed of multiple Unicode code points), occupying multiple screen columns, or something like that.

For context, the result would be used here:

https://github.com/ggandor/leap.nvim/blob/9a69febb2e5a4f5f5a55dd2d7173098fde917bc5/fnl/leap/search.fnl#L146-L148

**Comment by adriancmiranda** [comment]
Hey @ggandor.

I've been sick, but I just updated the plugin now and saw that you've already fixed it. I'll check out your solution. Thanks, man!
