### ISSUE TITLE
Add support for smartcase?

### ISSUE THREAD

**Issue by briandipalma** [ggandor/leap.nvim#109]
Basically if you type in an uppercase character make the search case sensitive?

**Comment by ggandor** [comment]
https://github.com/ggandor/leap.nvim/issues/28

**Comment by briandipalma** [comment]
Interesting, I looked for "smart" but it didn't show up that issue.

Anyway, as you say yourself in #28:

> It would work for the first input character

Plenty good enough for me, I'm constantly typing `sT` and then sighing as leap highlights matches for lower case `t`s. I've gone out of my way to type in an upper case letter as my first letter and yet leap ignores it. It seems perfectly reasonable that in such cases only upper case `T`s should match. Doing that would often cut down the matches significantly and allow me to use easier to reach labels instead of more awkward ones.

**Comment by briandipalma** [comment]
BTW I understand you say you "usually get a shorter route to the target" but I often find a single lower case match gets in the way of my uppercase match and if it wasn't there I could start editing immediately. So it's still a smoother flow if on the first character if it's uppercase the matches are smartcased.
