### ISSUE TITLE
Better highlight docs

### ISSUE THREAD

**Issue by Suyashtnt** [ggandor/leap.nvim#11]
After messing around for a while i still have no idea how to use the highlight groups for customizing leap nor do I know what group exactly highlights what. Maybe there can be some better clarification on how to customize the highlights

**Comment by ggandor** [comment]
> how to use the highlight groups for customizing leap

This is general (Neo)Vim knowledge, and does not belong to a plugin's documentation. That said: https://github.com/ggandor/lightspeed.nvim/issues/33 (Note that from 0.7 on, you can use `vim.api.nvim_set_hl(0, ...)` instead, see the built-in help.)

> nor do I know what group exactly highlights what

On the screenshot:

https://raw.githubusercontent.com/ggandor/leap.nvim/media/quick_example_3.png

- underlined: `LeapMatch` (note: as opposed to the screenshot, in the most recent version these are only shown if they cover a label)
- green labels: `LeapLabelPrimary`
- blue labels: `LeapLabelSecondary`
- everything else: `LeapBackdrop` (nothing by default, but you can customize)

**Comment by Suyashtnt** [comment]
thanks
