### ISSUE TITLE
option to ignore diacritics (feature request)

### ISSUE THREAD

**Issue by alexandreroberts** [ggandor/leap.nvim#117]
It would be nice to have the option to have Leap ignore diacritics on letters, for example treating `ṣ` and `š` as if they were `s`, or `ḥ` and `ḫ` as if they were `h`, or `ē` and `è` and `é` as if they were `e`, `ī` as `i`, `ā` as `a`, `ū` as `u`, etc. This feature would be analogous to the existing option to ignore case differences.

E.g., if my buffer has the word `ṣiḥḥah` in it somewhere after the cursor, I would like to be able to type `shh` to jump to the first `ḥ` in `ṣiḥḥah`.

Thanks for considering it -- and for writing this very useful plugin! I have been enjoying using it and find it even more elegant than Sneak.

**Comment by ggandor** [comment]
This is already possible:
```lua
leap.opts.equivalence_classes = { " \r\t\n", ""sṣš", "aàáâã", "uúûüű", ... }
```
Note: Obviously it has some performance penalty if you define huge eqivalence classes, since it increases the number of comparisons to be made per input character, but for a few diacritics it shouldn't be a problem.

**Comment by alexandreroberts** [comment]
Great, thank you! I didn't realize that. To save a bit of time for future Graeco-Arabists using NeoVim and Leap to write up their research (you never know, there might be another one!), I got exactly the behavior I wanted by adding this to my `plugin/leap.lua` file:

```lua
require('leap').opts.equivalence_classes = { " \r\t\n", "aäàáâãā", "dḍ", "eëéèêē", "gǧğ", "hḥḫ", "iïīíìîı", "nñ", "oō", "sṣš", "tṭ", "uúûüűū", "zẓ" }
```

Thanks again for the quick reply!
