### ISSUE TITLE
Single char leap at the end of the line does nothing

### ISSUE THREAD

**Issue by alexveden** [ggandor/leap.nvim#119]
My config:
```
            leap.add_default_mappings()
            leap.opts.safe_labels = {}
            leap.opts.highlight_unlabeled_phase_one_targets = true
```
When I press `<leap>{`, leaps failed when there is end of line straight after the `{`.

![image](https://user-images.githubusercontent.com/18488560/224380635-d36f2ee5-3a50-4fe9-83e6-0c5789db9004.png)

**Comment by ggandor** [comment]
There's no "single char leap" (`char<enter>` [traversal mode](https://github.com/ggandor/leap.nvim/tree/d34680b16af977928228e57c68e5a162f1649e3c#resolving-highlighting-conflicts-in-phase-one) is a different thing), you should press `space` (newline alias) after `{`. 

https://github.com/ggandor/leap.nvim/tree/d34680b16af977928228e57c68e5a162f1649e3c#jumping-to-the-end-of-the-line-and-to-empty-lines

https://github.com/ggandor/leap.nvim/tree/d34680b16af977928228e57c68e5a162f1649e3c#resolving-highlighting-conflicts-in-phase-one

**Comment by alexveden** [comment]
If I press `<leap>{<space>s` the cursor jumps to `{._.` label (in white) on the screenshot above. `<leap>{s<space>` also has no effect.

**Comment by alexveden** [comment]
Possibly the issue was caused, by `leap.opts.equivalence_classes{}` which didn't include  ' \t\r\n' values.

**Comment by ggandor** [comment]
> Possibly the issue was caused, by `leap.opts.equivalence_classes{}` which didn't include ' \t\r\n' values.

Well, if you don't show your whole config when opening an issue, it's hard to help :)
