### ISSUE TITLE
Configuration does not work 

### ISSUE THREAD

**Issue by Visual-Dawg** [ggandor/leap.nvim#122]
How do I properly configure the plugin?

When I add this config nothing gets set, except the default mappings:

```lua
use {
        'ggandor/leap.nvim',
        disable = false,
        requires = 'tpope/vim-repeat',
        config = function()
            local leap = require('leap')

            leap.opts.case_sensitive = false
            leap.opts.substitute_chars = {'\r\n<tab>', ')]}>', '([{<', {'"', "'", '`'}}
            leap.add_default_mappings()
            vim.api.nvim_set_hl(0, 'LeapBackdrop', {
                bg = '#1c1c1c'
            })
        end
    }

```

**Comment by ggandor** [comment]
> `vim.api.nvim_set_hl(0, 'LeapBackdrop', { bg = '#1c1c1c' })`

I think you wanted to say `fg = '#1c1c1c'` here.

> `leap.opts.substitute_chars = {'\r\n<tab>', ')]}>', '([{<', {'"', "'", '`'}}`

This should be `opts.equivalence_classes`.

> `leap.opts.case_sensitive = false`

This is the default by the way.

**Comment by Visual-Dawg** [comment]
Thank you, I changed the config (except the `bg` part, because I want it like that) , however it does still not work as expected:

```lua
local leap = require('leap')

leap.opts.equivalence_classes = {' \r\n\t', '([{<', {'"', "'", '`'}}
leap.add_default_mappings()

vim.api.nvim_set_hl(0, 'LeapBackdrop', {
    bg = '#1c1c1c'
})
```

When I `:source` this as a file, it works:
```lua
local leap = require('leap')

leap.opts.equivalence_classes = {' \r\n\t', '([{<', {'"', "'", '`'}}
leap.add_default_mappings()

vim.api.nvim_set_hl(0, 'LeapBackdrop', {
    bg = '#1c1c1c'
})
```

**Comment by ggandor** [comment]
Sorry, but I have no idea, this is an issue with Packer then, not Leap. (I know it's not an answer to the question, but I'd just use [paq](https://github.com/savq/paq-nvim), which is the simplest plugin manager out there, especially as a Vim newbie, and especially for a config as minimal as yours. Just `source` the plugin configurations from their dedicated file, as you do now, it's totally fine. Keep things simple.)
