### ISSUE TITLE
Help: Register additional operations during leap

### ISSUE THREAD

**Issue by rainzm** [ggandor/leap.nvim#123]
Hi. Thanks for your brilliant plugin. I very like and enjoy it.

When I use this plugin to jump in Chinese, I need to type 's', and then use `<C-Space>` to switch to Chinese, then enter two Chinese characters, then use `<C-Space>` switch to English, and select a label to jump.

I want to implement a specialized keybind(different from `t`) to simplify the operation of jumping between Chinese , but my skill is limited. I have read the documentation but still have some doubts about it.

I have now implemented two nvim commands(in fact, they are two lua function), namely "SwitchEnglish" to switch to English and "SwitchChinese" to switch to Chinese. But how to combine them into leap stumps me, can you give me a general idea?  I am very grateful for that.

**Comment by ggandor** [comment]
Hi, thank you very much for the kind words :)

This is not trivial. The first step is simple (switching to Chinese), you should simply wrap your helper function together with Leap and map it to your preferred key:

```lua
function ()
    switch_to_chinese()
    require('leap').leap { ... }
end
```

You could also switch back to English with an autocommand, on exit (that is, after selecting the label).
```lua
vim.api.nvim_create_autocmd('User', {
  pattern = 'LeapLeave',
  callback = switch_to_english,
})
```

The problem is we cannot hook into Leap before selecting the label (as of now).

**Comment by rainzm** [comment]
I use `xkbswitch` to implement the function of switching input methods. I found that my function works fine independently, but it doesn’t work when combined with leap. And the second part is not supported now, so I plan to give up this function temporarily. If there are more events about Leap in the future, I will consider this function again.

Thanks for your help.

**Comment by ggandor** [comment]
There is `LeapPatternPost` now, which is triggered after the full pattern is entered.

**Comment by rainzm** [comment]
@ggandor Thanks. It's very useful. I have perfectly realized the functions I envisioned.
