### ISSUE TITLE
Using semicolon (;) and comma (,) to repeat the last leap (and flit) motion?

### ISSUE THREAD

**Issue by andrevmatos** [ggandor/leap.nvim#128]
Hi,
Sorry if I didn´t  search enough, but I'd like to configure Leap to use `;` and `,` to repeat previous motion, and being able to keep repeating it, like Lightspeed:
https://github.com/ggandor/lightspeed.nvim/blob/299eefa6a9e2d881f1194587c573dad619fdb96f/doc/lightspeed.txt#L398-L408

Is it possible?
Thanks.

**Comment by ggandor** [comment]
Not possible at the moment. It is tricky to implement, Lightspeed's solution was kind of a hack.

**Comment by ggandor** [comment]
This is a reasonable request, given the plugin's aim of tight editor integration, and although I personally remap those, I see the value of `;`/`,` repeat, but Lightspeed's solution was a pretty ugly hack, I'm thinking about how to handle this.
