### ISSUE TITLE
Suggestion: small tweak to readme

### ISSUE THREAD

**Issue by mitchellwrosen** [ggandor/leap.nvim#141]
Hi there!

In the TL;DR section of the readme, after pressing `{c1}{c2}`, it states:

> If the pair was not labeled, then voilà, you're already there. No need to be bothered by remaining labels, just continue editing.

I think this is a bit misleading: you _are_ still bothered by the remaining labels, because if you press any of them, you will jump. So, perhaps it should mention something about pressing `<Esc>` in certain cases? I'm not sure the best course of action :)

Thanks!

**Comment by mitchellwrosen** [comment]
Oh, very interesting: I see later on this issue is mentioned:

> The labels for the subsequent matches of ol remain visible until the next keypress, but they are carefully chosen "safe" letters, guaranteed to not interfere with your following editing command.

Maybe no change is needed :)

**Comment by ggandor** [comment]
Yeah, that's the very idea :) `safe_labels` are, by definition, safe (or should be), that is, you _can_ ignore them.
