### ISSUE TITLE
Setting `max_phase_one_targets` seems to change where labels are drawn

### ISSUE THREAD

**Issue by mitchellwrosen** [ggandor/leap.nvim#142]
Hi there, apologies if this is intended behavior but I didn't see it documented anywhere.

I set out to configure `leap.nvim` to only show highlight groups after two keypresses. After setting `max_phase_one_targets = 0`, it seems that labels are now drawn _on top_ of their jump targets, rather than adjacent to them.

For example, with the default `max_phase_one_targets = nil` setting, I might type `sgi` and see:

<img width="511" alt="Screen Shot 2023-04-25 at 12 56 14 AM" src="https://user-images.githubusercontent.com/1074598/234177912-7270fcc6-c6fb-4a9a-bd4b-5e1c2a6bee07.png">

But with `max_phase_one_targets = 0`, I see

<img width="511" alt="Screen Shot 2023-04-25 at 12 56 40 AM" src="https://user-images.githubusercontent.com/1074598/234177970-ff07f661-718c-4a01-bf13-303bb58d1060.png">

So, the labels have moved two spaces to the left, and there also seems to be an extra space.

Thanks!

**Comment by ggandor** [comment]
Yes, this is intended, see #102. I didn't felt the need to explicitly mention this in the docs, but maybe we could do that.

**Comment by iHeadway** [comment]
> But with `max_phase_one_targets = 0`, I see

I wanted to try this, but setting it to 0 and 'highlight_unlabeled_phase_one_targets = false' didn't change anything for me.

**Comment by asmodeus812** [comment]
@ggandor I can not understand why when i type one character, the highlighting that is being shown, the labels make no sense, if i press any of the letters being shown after the first char i type, leap is just canceled.  For example i have a word "max",, i type "m", and a label will show over the letter "x" in "max".  It makes no sense, i would like to see the labels after i enter 2 characters not after the first one.  This is confusing since i can't tell how many characters i have entered, when typing fast.

**Comment by ggandor** [comment]
Why set it to 2? You should set the value to 0 to completely disable the feature (`:help leap.opts.max_phase_one_targets`).

**Comment by asmodeus812** [comment]
Neither 0 nil 1 or 2 do anything for me

**Comment by ggandor** [comment]
`require('leap').opts.max_phase_one_targets = 0` should work, the issue is something else then.

**Comment by asmodeus812** [comment]
Neither 0, 1 or nil work. Initially i was just setting it on a trial and error principle was too lazy to look at the source, and 2 worked, even then the docs seemed very poorly explained, there was no explanation on what phases are etc.
