### ISSUE TITLE
accept multiple sequential characters before tag selection

### ISSUE THREAD

**Issue by stupidanon** [ggandor/leap.nvim#144]
I really like this plugin but would prefer being able to do more than 2 characters, an arbitrary number preferably, similar to the below extension:
https://github.com/acejump/AceJump
Is this a possibility? Or must it be coded in? 
Thanks

**Comment by ggandor** [comment]
This is a fine candidate for an extension plugin (similar to Flit or Spooky). `HopPattern` might provide ideas for implementation.

Just water cooler chat, but may I ask why? Do you work on huge monitors, that is, with extremely big window areas, and have to switch groups lots of times? "Pattern" search would break [some of the key features](https://github.com/ggandor/leap.nvim#why-is-this-method-cool) that make Leap so enjoyable - making the steps so automatic that you can almost shut off your mind. You always have to finish the pattern with an `enter`, and you cannot see the labels ahead of time anymore. You also have to [be aware of the context](https://github.com/ggandor/leap.nvim#the-ideal) a bit more to decide whether the set of results is small enough to finally press that `enter` and select a label...

**Comment by stupidanon** [comment]
I think perhaps I did not fully explain what I was after in my post, sorry. So you start by pressing `f` to find, then you type in a letter. 

For example, in Leap, you want to jump to `Hello`, you press `H` and then two jumping characters to get there. 

What I am imagining is that you press `H` and then you have the option to press two jumping characters **OR** you can continue pattern matching by pressing `e`, then the jumping characters update based on the new pattern, closing in on your word. 

There is no need to ever press enter, and I think this is better because its faster for me to type out half of a word than it is to look at my screen and press two keys at random places on the keyboard. Typing out `Hel` is faster than typing out `H` then two random pattern keys. So you type out `Hel` then you probably narrowed it down enough to where there is only one jumping key on the screen, and you press that, and done. 

Let me know what you think.

**Comment by stupidanon** [comment]
But I do understand your argument, yes technically to make the optimal decision you have to be context aware which leads to making technically inefficient decisions

**Comment by stupidanon** [comment]
Something that maybe I could get along with is that When you select a character, Leap shows only the next possible jump character, and only when you press that, then it shows the next. 
Is it possible to show both characters immediately?

**Comment by ggandor** [comment]
> So you start by pressing f to find, then you type in a letter. For example, in Leap, you want to jump to Hello, you press H and then two jumping characters to get there.

I don't understand this. Are you talking about Flit? In Leap, you should press two characters you do see (`He`), and then one label character (or zero... or space-space...label).

**Comment by stupidanon** [comment]
My apologies. Somehow, it seems when I last edited it, I set settings that I now find inferior, i reset the plugin and it works great. Again, sorry to waste your time.
