### ISSUE TITLE
Mapping keys while entering the search pattern

### ISSUE THREAD

**Issue by Sleepful** [ggandor/leap.nvim#147]
I like to have some remaps in insert mode:
```lua
    vim.keymap.set("i", "$", "{")
```
but these are not reflected when I try to do `s$ `.
I expect this combo to result in `s{ ` but it does not map the `$` into `{` while searching.

I also tried modes `x o l v` to no avail.
The issue is also present in flit.nvim

**Comment by Sleepful** [comment]
After searching around a bit, it looks like this is a vim limitation. For example, it seems impossible to remap the `char` after the standard `r` operation `r{char}`. Feel free to close issue.

**Comment by ggandor** [comment]
`:h language-mapping` or `:h mbyte-keymap` is what you're looking for, I guess.

**Comment by ggandor** [comment]
@Sleepful

**Comment by Sleepful** [comment]
I ended up giving up on `mbyte-keymap` due to complexity in different scenarios, instead I moved to a combination of binding at the `terminal emulator` level and at the `nvim_set_keymap` level.
