### ISSUE TITLE
Not jumping and labels are misplaced

### ISSUE THREAD

**Issue by lfilho** [ggandor/leap.nvim#148]
Hey @ggandor thanks for the plugin and all the effort put in it!

Similar to #113, I'm getting a weird behavior where it is not jumping and additionally, the labels seem to be placed on the wrong places. Screenshots below.

Using latest versions of the plugin, nvim 0.9, Lazy.nvim and AstroNvim (pretty sure shouldn't matter).

Here's my Lazy.nvim config:

```lua
{
      event = { "VeryLazy" },
      "ggandor/leap.nvim",
      keys = {
        { "<Plug>(leap-forward-to)", mode = { "n", "x", "o" } },
        { "<Plug>(leap-backward-to)", mode = { "n", "x", "o" } },
        { "<Plug>(leap-from-window)", mode = { "n", "x", "o" } },
      },
      config = function(_, opts)
        local leap = require("leap")
        for k, v in pairs(opts) do
          leap.opts[k] = v
        end
        vim.keymap.set({ "n", "x", "o" }, ",s", "<Plug>(leap-forward-to)", { desc = "Leap forward" })
        vim.keymap.set({ "n", "x", "o" }, ",S", "<Plug>(leap-backward-to)", { desc = "Leap backward" })
        vim.keymap.set({ "n", "x", "o" }, "gs", "<Plug>(leap-from-window)", { desc = "Leap from window" })
      end,
    }
```

**Notes about the config above:**
1. I remove the "event ="  line the plugin doesn't get activated at all (we don't even get to the wrong behavior that I'll describe below)
2. I want to use `,s` and `,S` as my keymaps since `s` is already taken by `mini.surround` plugin.

Now, here's a screenshot of where my cursor is:

![image](https://user-images.githubusercontent.com/282756/236701251-af10bcc4-b8f0-4fbc-baef-6424fa267b39.png)

Now if I type `,s=`, I would expect label on the `=` chars, right? But this is what I get:
![image](https://user-images.githubusercontent.com/282756/236701405-8feed9f0-4a00-4d4a-a5f8-fc2b54a33dd2.png)

Note how it seems to be shifted by 2 chars. Additionally, if i actually select any of them (let's say the first one in there, labelled `s`), it doesn't jump at all and the cursor stays where it is. 

Any clue? Thanks a lot

**Comment by rish987** [comment]
To give you a quick answer, you actually need to use two characters to complete the search -- see the [usage](https://github.com/ggandor/leap.nvim#usage) section of the README. The hints are offset by two characters so that you're still able to see the second character that you need to type (that is, this is a feature of `leap.nvim`).

**Comment by ggandor** [comment]
@lfilho
