### ISSUE TITLE
Third character is not displayed distinctly in VSCode (when using neovim extension)

### ISSUE THREAD

**Issue by nhuhoang0701** [ggandor/leap.nvim#15]
I tried to use leap.nvim in VSCode by using neovim extension). However, for some reason, the third character is only displayed as the same character of the word, not a different character to jump (the image below is for key sequence `sco`). I think this is only a display issue because when I type `s` or `f` after that sequence, the cursor jumps to the second and the third word which is the same behavior when I tried it with neovim.

![image](https://user-images.githubusercontent.com/40765474/165413101-ab5662e7-8686-4dce-b542-fa46e01a118b.png)

OS: Arch Linux 5.17.4
VSCode: 1.66.2
neovim: 0.7.0

**Comment by ggandor** [comment]
The developments can be followed [here](https://github.com/vscode-neovim/vscode-neovim/pull/868).

**Comment by thisisphan** [comment]
Is that why Leap's auto jump won't highlight the cursor until a movement key is pressed? (in vscode)

**Comment by theol0403** [comment]
> Is that why Leap's auto jump won't highlight the cursor until a movement key is pressed? (in vscode)

Yes

**Comment by ggandor** [comment]
> Ideally this "fake cursor" workaround can be removed

Hopefully that will indeed be possible, sooner or later: https://github.com/neovim/neovim/pull/19035

**Comment by trkoch** [comment]
> Extmark/lightspeed/leap is now supported in vscode! One problem is that vscode blocks the `Cursor` hl from being sent from neovim. Since there is not an equivalent to `LightspeedCursor`, this breaks leap. Ideally this "fake cursor" workaround can be removed, or a `LeapCursor` hl is supported.

You can workaround with the vscode-neovim `highlightGroups.highlights` setting:

```json
"vscode-neovim.highlightGroups.highlights": {
    "Cursor": {
      "backgroundColor": "theme.editor.findMatchBackground",
      "borderColor": "theme.editor.findMatchBorder",
    },
  },
```

Here I'm referencing a theme color. You can also define a CSS color directly or set other other attributes such as or `fontStyle` or `textDecoration`.

**Comment by theol0403** [comment]
Actually, workarounds are no longer needed for leap to work in latest vscode-neovim!

**Comment by trkoch** [comment]
> Actually, workarounds are no longer needed for leap to work in latest vscode-neovim!

I'm referring to this.

> Is that why Leap's auto jump won't highlight the cursor until a movement key is pressed? (in vscode)

Setting `highlight Cursor cterm=reverse gui=reverse` had no effect in my case.

**Comment by theol0403** [comment]
Yes, that has been fixed last week. You don't need to change the highlight.

Try with empty vscode settings.json.

**Comment by kevintraver** [comment]
Plugin has been working great with **VSCode neovim**

The only feature I've found that does not work is _cross-window motions_
