### ISSUE TITLE
feat: semi-inclusive op

### ISSUE THREAD

**Issue by IndianBoy42** [ggandor/leap.nvim#152]
i've been thinking about selection mappings and thought of an alternative that I would like to try, which is visual/operator mode leaping that includes the first character but excludes the second character. I think this could be pretty intuitive in terms of what you see when looking at the place I want to select to. If you think of selections as going to/from the space between characters then this semi-inclusive mode would be targeting based on the characters around that space. 

Usually I would just implement this myself to try it and then submit a PR but I don't know fennel at all

**Comment by ggandor** [comment]
`require('leap').leap { offset = 1, incusive_op = true }` (n.b., this was the original behavior, it was changed later, inspired by evil-snipe).

**Comment by IndianBoy42** [comment]
That works! I forgot about the offset parameter. thanks, lets see how I feel about this
