### ISSUE TITLE
Support one-way aliases

### ISSUE THREAD

**Issue by mitchellwrosen** [ggandor/leap.nvim#155]
Hi there, I'd like to propose a feature similar to `equivalence_classes`, but one-way.

As a motivating example, suppose I want to make the `.` character equivalent to any special character, because it's easier to type than most:

```
equivalence_classes = { ".`~!@#$%^&*()-_=+[{]}\\|;:'\",<>/?" }
```

This works okay, but it does prevent me from ever jumping to (say) the comma character in this sequence:

```
","
```

because it's equivalent to an overlapping sequence of three dots:

```
...
```

If I could ask leap to treat `.` as any operator character, but _not_ the other way around, then I could jump to the middle comma in the above example with `s,"<label>`, as usual.

Thanks!

**Comment by ggandor** [comment]
I should probably create a FAQ entry, this is an obvious request, but - just like smartcase - impossible by design: https://github.com/ggandor/leap.nvim/issues/89#issuecomment-1368885497.

**Comment by mitchellwrosen** [comment]
Thanks, I trust your assessment, but I'm not sure I understand.

> Think about it: when targeting k+, after pressing k, the plugin cannot know whether you will type + or * (the wildcard character), so it cannot decide which label to show (the labels are different in the two cases, since the wildcard would match a lot more targets).

Why must the plugin know whether you will type `+` or `*` after `k` in this example? I should think that after a single `k`, we'll get a label after every `k<c>` pair, and pressing `*` would simply drop no labels (because all `k<c>` match).

Or, in my example, I don't exactly have a wildcard, but I would think that after (say) `j.`, we could leave a label after every `j!`, `j@`, `j#`, etc. in the buffer.

**Comment by ggandor** [comment]
> I should think that after a single k, we'll get a label after every k<c> pair, and pressing * would simply drop no labels (because all k<c> match).

The problem is that in phase 1 there are conflicting labels, you cannot just keep all of them. Each sublist of targets gets labeled by the same label list, e.g. `ka`s get l1, l2, l3..., and `kb`s also get l1, l2, l3... The ambiguity is only resolved in phase 2, once you enter the second character, and only the chosen sublist remains.

**Comment by mitchellwrosen** [comment]
Oh, of course. I hadn't ever noticed that labels conflict but that does make sense!
