### ISSUE TITLE
highlight groups get overriden when `:colorscheme` is used

### ISSUE THREAD

**Issue by einiges** [ggandor/leap.nvim#16]
Just noticed that setting the leap highlight groups (_LeapMatch_, …) in a colorscheme has no effect. Well it has when the file is `:source`d, but not when set correctly with `:colorscheme theme`.

It happens because the `ColorScheme`-event, for which an autocmd is set up, gets triggered.
https://github.com/ggandor/leap.nvim/blob/b0921b7fedefb8d0251052cbc9975be616810846/fnl/leap.fnl#L1000-L1010

**Comment by ggandor** [comment]
Interesting... That autocommand shouldn't cause any problems, since `init-highlight` uses the `default` key for each of the groups.

**Comment by ggandor** [comment]
Got it, thanks for pointing this out!
