### ISSUE TITLE
support bidirectional motions

### ISSUE THREAD

**Issue by perrin4869** [ggandor/leap.nvim#160]
coming from a `hop.nvim` (and before that, from `vim-easymotion`), I'm used to bidirectional searches. Sometimes I find myself triggering a forward search when trying to jump to a character behind my cursor.
It seems [`vim-easymotion` supports this](https://github.com/easymotion/vim-easymotion#bidirectional-motions) as of right now, I was wondering if `leap.nvim` is going to support this too?

**Comment by ggandor** [comment]
[FAQ](https://github.com/ggandor/leap.nvim#faq) :)
