### ISSUE TITLE
The search does not start with `s` key press as stated in the docs, it instead deletes a character under the cursor and enters insert mode

### ISSUE THREAD

**Issue by bashonregardless** [ggandor/leap.nvim#162]
The plugin is installed @ path _~/.local/share/lunarvim/site/pack/lazy/opt/leap.nvim_

I use LunarVim.

**Comment by ggandor** [comment]
Have you defined keymappings? (`require('leap').add_default_mappings()` or custom ones)

**Comment by bashonregardless** [comment]
> 

Add the the `require('leap').add_default_mappings(true)` did the trick.
Now I am thinking whether I should remap original `s` and `S`. I used `s` heavily.

**Comment by bashonregardless** [comment]
Thanks @ggandor 
Closing this!

**Comment by ggandor** [comment]
> I used s heavily

IMHO using `cl` and `cc` is as comfortable as it gets.
