### ISSUE TITLE
[Feature?] Display labels for targets on columns that are outside of the window view past the RIGHT border

### ISSUE THREAD

**Issue by Sleepful** [ggandor/leap.nvim#163]
Currently if a target is outside of the window view past the LEFT border, leap handles it very nicely and displays the label for the target next to the left border and handles the jump correctly, moving the cursor PAST the left border until it finds the real target.

However, if the target is outside of the window view past the RIGHT border of the window, leap will not display the label. HOWEVER Leap _still_ places the target because if you guess the right letter that leap would assign to the label, then it effectively jumps outside of the screen. The problem is that the user just can not see the label because the label is not shifted into window view.

This cannot be remedied for _particular_ targets with the `offset` because `offset` affects all targets, and only _some_ targets will be off the screen.

Thanks!

**Comment by ggandor** [comment]
> it doesn't make sense to feed invisible targets to Leap in the first place

But even if someone does show me a legitimate use case, it's possible to handle it correctly even now. They can use the `pos` field of the target as the label's position, and also register the position for the action in another field, let's call it `action_pos`, and along the custom `targets`, give a custom `action` too to Leap, that uses that `action_pos` instead of `pos`.

```
leap {
   targets = <potentially off-window targets with both `pos` and `action_pos` field>,
   action = function (target) <jump to or do something with `target.action_pos`> end
}
```

**Comment by Sleepful** [comment]
Thanks for reply! 

Yeah I found this behavior through the [linewise motions example](https://github.com/ggandor/leap.nvim/blob/main/README.md?plain=1#L596-L639) from the README.

The function jumps to the first column of each line, so if the first column is outside of vision, you can still jump there.

Cool!

You could easily think of a similar function that would be jumping to the other side: Jump to end of each line. This one will not display all the labels! 

Not actually what I am using it for but this is the simplest example.

Currently I am using leap to jump to specific words, and sometimes I remember the word that I want to jump to even if it is out of view, heh...

> what should happen if there are multiple off-window targets on the same line?

Yeah that is difficult to solve as a 'default'. I do not think a 'default' is the best idea either, but the option for the user to customize the label positioning and colors.

> But even if someone does show me a legitimate use case, it's possible to handle it correctly even now.

Yes! This is what I was looking for. Awesome, that solves it for me, thanks for thinking through this, I could not figure out that `action` solves it

😁
