### ISSUE TITLE
Error detected while processing User Autocommands for "LeapEnter"

### ISSUE THREAD

**Issue by hrcHarry** [ggandor/leap.nvim#164]
## Installation:
By Packer

## Configuration:
`require('leap').add_default_mappings()` (in `init.lua`)

## Description: 
In any file, typing `s` or `S` will result in the error shown as follows
![](https://upload.cc/i1/2023/06/23/4ojLJK.png)
This still happens even if I remove and install leap.nvim again.

## Expected behavior:
`s` and `S` can normally function.

**Comment by mnoukhov** [comment]
Seems related to 854d7639c7928d74a7401c5791aca2a6372e6e0c

Looks like it's a relatively new API (see https://github.com/neovim/neovim/issues/22679) and your neovim version should be updated to 0.9+

Another option is to change the code to use `nvim_get_hl_by_name` but that may be deprecated in the future (according to the neovim issue)

**Comment by ggandor** [comment]
Thanks :)
