### ISSUE TITLE
nvim_get_hl is nil value

### ISSUE THREAD

**Issue by SolaWing** [ggandor/leap.nvim#167]
I am use nvim-0.83,
(vim.fn.has "nvim-0.9") returns 0, not false, and it called nvim-0.9 api

**Comment by ggandor** [comment]
Thank you very much, this always trips me up!

**Comment by SolaWing** [comment]
@ggandor should use 0.9 api when ~= 0

**Comment by ggandor** [comment]
Lol... right :)
