### ISSUE TITLE
Bug: too many arguments for function `strcharpart`

### ISSUE THREAD

**Issue by delatorrejuanchi** [ggandor/leap.nvim#171]
It seems 66f055ab20b4678a2b9d13c4de791355917ccbd3 may have introduced a bug.

# Description

Trying to initiate a search fails with the following error:

```
E5108: Error executing lua: Vim:E118: Too many arguments for function: strcharpart
stack traceback:
        [C]: in function 'strcharpart'
        .../.local/share/nvim/lazy/leap.nvim/lua/leap/highlight.lua:66: in function 'highlight-cursor'
        .../.local/share/nvim/lazy/leap.nvim/lua/leap/main.lua:730: in function 'get_first_pattern_input'
        .../.local/share/nvim/lazy/leap.nvim/lua/leap/main.lua:987: in function 'leap'
        .../.local/share/nvim/lazy/leap.nvim/plugin/init.lua:25: in function <.../.local/share/nvim/lazy/leap.nvim/plugin/init.lua:24>
```

# Config

Using a base NvChad setup with the following configuration

```lua
local plugins = {
  ...

  {
    "ggandor/leap.nvim",
    lazy = false,
    config = function()
      require("leap").add_default_mappings()
    end,
  },
}
```

**Comment by kinyoubi1009** [comment]
Experiencing the same issue with LazyVim. 

`vim.fn.strcharpart` 

only takes 3 arguments but in highlight.lua and search.lua, 4 arguments are used:

`strcharpart(line_str, start, 1, 1)`

**Comment by jam1015** [comment]
confirmed. temproarily fixed by rolling back to the previous commits for `leap` and `flit`.

```    {
		"ggandor/flit.nvim",
		commit = "5c9a78b97f7f4301473ea5e37501b5b1d4da167b",
	},
	{
		"ggandor/leap.nvim",
		commit ="8facf2eb6a378fd7691dce8c8a7b2726823e2408",
	},
```

**Comment by kinyoubi1009** [comment]
changing 

`strcharpart(line_str, start, 1, 1)`

to 

`strcharpart(line_str, start, 1)`

for all instances of `strcharpart()` in `leap` and `flit` seems to fix the error.

**Comment by ggandor** [comment]
Oops, this is a recent addition: https://github.com/neovim/neovim/commit/3724e65c30f7d1ef803ac4e34eab7d4a9531b1a8.
