### ISSUE TITLE
Is there some key I can press to tell leap to match any character after the first one?

### ISSUE THREAD

**Issue by Exlll** [ggandor/leap.nvim#174]
I'm often in the situation in which I want to jump to a character that is surrounded by characters that are annoying to type, as they require me to press some modifier keys to input them. For example, all sorts of brackets fall into this category (on my keyboard layout). Some concrete examples of these are:

* `fn some_func(n: i32) {}`, jump to the space between `) {` to add a return type
* `println!("print {x}")`, jump to `x` and rename the variable
* `<a>`, jump after the `a` and add some attributes

Is there some key I can press to tell leap to match any character after the first one? I've read this Reddit post [leap.nvim: 1-char mode (of sorts) ](https://www.reddit.com/r/neovim/comments/tvz5zx/leapnvim_1char_mode_of_sorts/), but this is not quite the functionality I need; I'd prefer if there was some `{key_to_match_any_char}` key I could press as a second character which would leave all the labels that appreared after the first character press as is. So, for example, I would like to be able to press `sx{key_to_match_any_char}` to show labels for all appearances of `x` and then select one of the labels to jump to the specified `x`.

**Comment by ggandor** [comment]
> which would leave all the labels that appreared after the first character press as is

That could not work, since in the first phase there are (potentially) multiple instances of the same label character.

> I'm often in the situation in which I want to jump to a character that is surrounded by characters that are annoying to type

This is an XY problem then, I think the solution is to use `equivalence_classes`. For example, `opts.equivalence_classes = { " \t\r\n", ";()[]{}" }`, so that `;` will match brackets (and itself), but of course, experiment and try to find a good arrangement.

**Comment by Exlll** [comment]
Awesome! Already feels much better :-) Thank you, and sorry for opening yet another similar issue.
