### ISSUE TITLE
Plug cannot find the target when I input only one character and a mark, but it works when I input two characters and a mark

### ISSUE THREAD

**Issue by ruinb0w** [ggandor/leap.nvim#177]
![Screenshot 2023-07-19 at 15.54.34.png](https://s2.loli.net/2023/07/19/UWTKB7ksXu4eQ9S.png)
![Screenshot 2023-07-19 at 15.48.40.png](https://s2.loli.net/2023/07/19/3tVCrPaS2NFDfeb.png)

I’m trying to jump to **systemInfo** at line 28, so I typed `s` `s` `l` plug say **not found sl**.  Then I tried `s` `s` `y` `l` and it worked.

Is this a bug?

**Comment by ggandor** [comment]
https://github.com/ggandor/leap.nvim#how-to-use-it-tldr

**Comment by ruinb0w** [comment]
thank you for you answer, and sorry for my missing
