### ISSUE TITLE
Feature Request: Set Default Keymaps for Specific Modes

### ISSUE THREAD

**Issue by kevintraver** [ggandor/leap.nvim#181]
I have found the default keymaps in normal mode (e.g., `s/S`) very useful while working with `leap.nvim`. However, I've also encountered situations where I want to disable specific keybindings for visual and operator modes (like `cs`, `ds`).

It would be awesome to have a configuration option that allows the enabling of the default keymaps in normal mode while simultaneously providing the ability to selectively disable specific keybindings in other modes.

A possible implementation could include a method to configure modes, such as:

```lua
require("leap").add_default_mappings( { modes: { 'normal', 'visual', 'operator' } } )
```

This would define the modes in which default mappings should be active, giving control to exclude or include specific modes as needed.

**Comment by ggandor** [comment]
In that case simply define mappings manually, `vim.keymap.set` even allows you to give a list of modes: 
```
vim.keymap.set(<modes>, 's', '<Plug>(leap-forward-to)')
vim.keymap.set(<modes>, 's', '<Plug>(leap-backward-to)')
```

**Comment by kevintraver** [comment]
Thanks!

This works great:

```
vim.keymap.set({ "n" }, "S", "<Plug>(leap-backward-to)")
vim.keymap.set({ "n" }, "s", "<Plug>(leap-forward-to)")

vim.keymap.set({ "o", "x" }, "Z", "<Plug>(leap-backward-till)")
vim.keymap.set({ "o", "x" }, "z", "<Plug>(leap-forward-till)")

 ```
