### ISSUE TITLE
How does operator work?

### ISSUE THREAD

**Issue by crhf** [ggandor/leap.nvim#182]
Thanks for this great plugin! I'm having a small issue with it.

I have the text `import glob`, with the cursor at the beginning. Under normal mode, I type `dso`. I expect two labels to pop up for the two o's. But the two o's are immediately deleted, and I get `imprt glb`. Do you have idea about what's happening here?

**Comment by ggandor** [comment]
> I expect two labels to pop up for the two o's

You don't necessarily see labels, `or` and `ob` might be unique matches.

> But the two o's are immediately deleted, and I get `imprt glb`.

I cannot reproduce, and have no idea what's happening, unfortunately... What does `:omap s` show?

**Comment by crhf** [comment]
Ah, it was vim-surround deleting the surrounding `o` :) After disabling vim-surround, things work as expected.

Do you also have issues with vim-surround?

`:omap s` gives
```
o  s           * <Plug>(leap-forward-to)
                 Leap forward to
Press ENTER or type command to continue
```
which is to be expected.

**Comment by ggandor** [comment]
Ah, surround, I never would have thought... See https://github.com/ggandor/leap.nvim/discussions/38 & https://github.com/justinmk/vim-sneak/issues/268#issuecomment-757135567.
