### ISSUE TITLE
gs not added to jump list?

### ISSUE THREAD

**Issue by crhf** [ggandor/leap.nvim#187]
### What I did

Jump from buffer A to B with `gs`, then press `Ctrl-O`.

### Expected behavior

Cursor goes back to A.

### Actual behavior

Cursor goes to the last location in jumplist in buffer B.

**Comment by ggandor** [comment]
There is a separate jumplist for each window (`:h jumplist`). Our behavior is consistent with the rest of Vim, if you switch windows, e.g. with `ctrl-w`, it never adds the position in the source window to the target window's jumplist.
