### ISSUE TITLE
Pressing s enters substitute instead of leap

### ISSUE THREAD

**Issue by mrafaeldie12** [ggandor/leap.nvim#19]
Hey, relatively new to vim, Love the idea of leap and wanted to try it out. Unfortunately after adding it to my init.lua, saving, sourcing, and running packer install pressing `s` causes me to substitute instead of triggering leap. I checked that leap is successfully installed by running `:help leap`. Is there anything else I need to do?

**Comment by ggandor** [comment]
Yep, also add `require('leap').set_default_keymaps()` to your init.lua, Leap doesn't remap its default keys automatically (as opposed to Lightspeed). https://github.com/ggandor/leap.nvim#installation :)

**Comment by mrafaeldie12** [comment]
🤦 I forgot to resource my `init.lua` after adding that line, hence why it was not working. Thank you for the prompt reply! 🚀
