### ISSUE TITLE
how to sponsor you

### ISSUE THREAD

**Issue by looshch** [ggandor/leap.nvim#192]
leap.nvim is incredible, how can i sponsor you?

**Comment by teocns** [comment]
@ggandor

**Comment by ggandor** [comment]
Yep, I'm here, thanks very-very much for the kindness and support for everyone, so, at the moment, there's no official channel for that, but I will let you know folks once/if you can "buy me a coffee" or something like that :) (It just seems like too much administrative hassle [I mean tax-wise] compared to the potential amount received, if only a handful of people are interested, and my OSS portfolio is basically just this one [major] project right now.)
