### ISSUE TITLE
Disable the secondary labels completely

### ISSUE THREAD

**Issue by fredizzimo** [ggandor/leap.nvim#194]
The secondary blue labels confuse me, when I see a label I automatically press the key, which jumps to the wrong location and waste a lot of time. I'd rather take take the additional hit of a reaction time and only have them show  only after I press space. The case is also rare enough that it's heard to build a muscle memory of automatically pressing space when you see the color blue.

I tried a few different things, but it looks like there's no way to disable this in the configuration.

**Comment by ggandor** [comment]
You can link the `LeapLabelSecondary` highlight group to `Normal` (i.e. make it transparent) or hide only the letters by setting the foreground color the same as the background color (that way you keep a visual indication that the target is labeled).

**Comment by fredizzimo** [comment]
Thanks, I ended up doing the following to just make the text invisible, and uses the colorscheme background color. This also fits well with having to press space.
```lua
local secondary_hl = vim.api.nvim_get_hl(0, {name = "LeapLabelSecondary"})

vim.api.nvim_set_hl(0, "LeapLabelSecondary",{
    fg = secondary_hl.bg,
    bg = secondary_hl.bg,
})
```
