### ISSUE TITLE
Setup failed: attempt to index field 'keymap' (a nil value)

### ISSUE THREAD

**Issue by yetone** [ggandor/leap.nvim#2]
<img width="1079" alt="image" src="https://user-images.githubusercontent.com/1206493/159833310-10d8f768-6525-44e3-bd27-ba4a1ea32c14.png">

**Comment by ggandor** [comment]
You need to use 0.7.0-dev for Leap (`vim.keymap.set` is missing).

**Comment by yetone** [comment]
@ggandor thank you!
