### ISSUE TITLE
Leap doesnt seem to be working properly

### ISSUE THREAD

**Issue by Suyashtnt** [ggandor/leap.nvim#20]
after I installed the plugin and tried to search for something, I typed `sli` expecting to be able to jump to `symbols_outline`, but all I get is this strange highlight.
![image](https://user-images.githubusercontent.com/45307955/173391193-5da78746-4ab6-4df6-bd9c-e4bd118f5606.png)

Config for leap: 
```lua
require("leap").setup({})
``

**Comment by ggandor** [comment]
Interesting. In theory, `require("leap").setup({})` should not change the defaults at all, but there's absolutely no need for calling `setup` with an empty table - try removing that line from your config. It seems that somehow the `opts` table - which includes the list of label characters - has been deleted.

**Comment by Suyashtnt** [comment]
I'm using light speed rn, I'll let you know if your suggestions help

**Comment by ggandor** [comment]
See [#21](https://github.com/ggandor/leap.nvim/issues/21#issuecomment-1156117115).
