### ISSUE TITLE
Set vim.g.loaded_leap = 1 when plugin loaded

### ISSUE THREAD

**Issue by HaleTom** [ggandor/leap.nvim#200]
I'm trying to determine whether or not leap has been loaded (because I'm setting up remotions for its mappings iff it is loaded).

Currently, I'm adding my own `vim.g.loaded_leap = 1` in my lazy.nvim `config()` after loading leap.

This variable follows the vim convention for plugins:
https://vimhelp.org/usr_51.txt.html#:~:text=Then%20the%20user,are%20added%20twice.

Is there a better way to determine if leap is currently loaded?  Would you consider setting this variable yourself to follow convention?

**Comment by ggandor** [comment]
For Lua plugins, there's no need for that, it's just: `if package.loaded['leap'] then ... end` (`require` checks this very table too before loading modules). https://www.lua.org/manual/5.1/manual.html#pdf-require

**Comment by HaleTom** [comment]
Thanks!  The not-yet-loaded version is:

```
---@param plugin string
function has_lazy_nvim_plugin(plugin)
  return require("lazy.core.config").spec.plugins[plugin] ~= nil
end
```

Shamelessly borrowed from LazyVim :)
