### ISSUE TITLE
Config example for bidirectional search

### ISSUE THREAD

**Issue by skanti** [ggandor/leap.nvim#201]
Hi,
I'm struggling to understand how to activate bidirectional search because I believe the documentation is impartial or only vaguely explains how to do it. Could you please add a working example to the doc?

**Comment by ggandor** [comment]
Hi! What is unclear about the snippet? This is all what you have to do. (`<modes>` is e.g. `{'n', 'x', 'o'}`, `<key>` is the key you want to use, e.g. `'s'`. `:help vim.keymap.set`)
```
vim.keymap.set(<modes>, <key>, function ()
  require('leap').leap { target_windows = { vim.api.nvim_get_current_win() } }
end)
```

**Comment by ggandor** [comment]
6362976
