### ISSUE TITLE
The jump position key if starts with a vim motion it would trigger the motion after jumping to that postion

### ISSUE THREAD

**Issue by Hamza12700** [ggandor/leap.nvim#203]
# The problem

If the jump position letter starts with a vim motion for example `i` or `a` when pressed it would jump to the position but it also triggers the vim motion too.

You can see in this video that the jump position letter is a vim motion `v - Visual mode`:

https://github.com/ggandor/leap.nvim/assets/72913359/5b7584f4-0d4c-4c1d-84ab-79ec0335253c

**Comment by ggandor** [comment]
That `v` is not a label, but the cursor itself. See:
https://github.com/ggandor/leap.nvim?tab=readme-ov-file#installation ("Workaround...")
https://github.com/ggandor/leap.nvim/issues/70

**Comment by Hamza12700** [comment]
> That `v` is not a label, but the cursor itself. See https://github.com/ggandor/leap.nvim?tab=readme-ov-file#installation ("Workaround..."), and #70.

I tried the snippet code but doesn't work.
It hides the cursor and still triggers the vim motion.

The `neovim` version:
```bash
NVIM v0.10.0-dev-35f453f
Build type: RelWithDebInfo
LuaJIT 2.1.1707061634
Run "nvim -V1 -v" for more info
```

**Comment by Hamza12700** [comment]
> Leap jumps to the first target automatically, without having to use a label (`:help leap-usage`, `:help leap-smart-autojump`). The `v` you see is the (fake) cursor on the first letter of the match (`vi`), not a label. You can see that it has a different color.

Should've read the friendly manual
