### ISSUE TITLE
Option to disable autojump behavior **completely**

### ISSUE THREAD

**Issue by wis** [ggandor/leap.nvim#206]
Hello, thanks for building this awesome plugin! I would like to disable auto jumping **completely**, to make the behavior of Leap predictable <sup>(and to make developing muscle memory faster and make the muscle memory itself more ingrained, and therefore make using Leap faster)</sup>, i.e. I want to _always_ use 3 key presses to jump, or if you include the `s`, 4 key presses: `s{char1}{char2}{label} `. always using 4 key presses is predictable and predictable is fast. it also leaves no room for errors, making you even faster. 

in #37, you [say](https://github.com/ggandor/leap.nvim/issues/37#issuecomment-1206209306):
> We're doing something better: by adding/removing elements to/from labels and safe_labels, you can fine-tune the autojump behaviour. If you want to disable it completely, simply set safe_labels = {}.

I have the following in my init.lua:
``` lua
  {
    'ggandor/leap.nvim',
    config = function()
      require('leap').create_default_mappings()
      require('leap').opts.safe_labels = {} -- disable autojump?
      require('leap').opts.labels = 'tnseriaoplfuvmwyqjc,x.' --home row & least effort keys for Colemak layout
      vim.keymap.set({ 'n', 'x', 'o' }, 't', '<Plug>(leap-forward)') -- use t and T instead of s and S
      vim.keymap.set({ 'n', 'x', 'o' }, 'T', '<Plug>(leap-backward)') 
    end,
  },
```

Note how I set `safe_labels` to an empty table or empty string, as [recommended](https://github.com/ggandor/leap.nvim/blob/6ef54268ba9e36bf6ea92c521059041848477e7e/README.md#phase-two), still after doing that, it still auto jumps to first occurrence if the first 2 characters match only 1 occurrence, and removes the labels and goes into normal mode. I would like to disable this behavior also, I would like to always use the label after the 2 characters, to make the use of Leap predictable, and fast, through muscle memory.

Edit: seems like you agree with me on this principle that I'm trying to explain, György, in discussion #59 you explain: 
> Having efficient shortcuts for frequent commands is very important, but consistency matters more than saving a keystroke in all possible situations, as cognitive friction slows you down ultimately.

Consistent behavior = predictableness = less cognitive friction = more-ingrained/stronger muscle memory = fast

**Comment by ggandor** [comment]
Thank you :) This is a bug (indeed, I can reproduce), it is intended work now as you described: https://github.com/ggandor/leap.nvim/issues/107.
