### ISSUE TITLE
Initial label not showing properly

### ISSUE THREAD

**Issue by dmun** [ggandor/leap.nvim#208]
Initial label is blank when `{char1}` == `{char2}`, and `{char2}{?}` pair does not have a label.

Example when leaping to `--` in the following clip:

[![asciicast](https://asciinema.org/a/646152.svg)](https://asciinema.org/a/646152)

**Comment by ggandor** [comment]
Interesting. This behavior is intended, see https://github.com/ggandor/leap.nvim?tab=readme-ov-file#special-cases (concealed labels), but labels should not overlap each other in the middle of the line... Could you paste the buffer content here, so that I can experiment/reproduce?
