### ISSUE TITLE
Dot repeat not working

### ISSUE THREAD

**Issue by jannes** [ggandor/leap.nvim#214]
Hi, I have installed both vim-repeat and this plugin through lazy.nvim as follows:
```
  ...
  'tpope/vim-repeat',
  {
    'ggandor/leap.nvim',
    config = function()
      require('leap').create_default_mappings()
    end,
  },
  ...
```

However, using `.` to repeat last search by `leap.nvim` does not work, it repeats the last other repeatable action.
What could be the problem here?

**Comment by ggandor** [comment]
I don't use lazy, but maybe try specifying the dependency explicitly:
```
  {
    'ggandor/leap.nvim',
    dependencies = { 'tpope/vim-repeat' },
    ...
  },
```

**Comment by jannes** [comment]
Thanks for the quick response, I did actually try that among other things after opening the issue and I did not change anything.

So you can confirm that for you using "." does work with latest master? If so, I will investigate further what's the problem with my specific setup.

**Comment by ggandor** [comment]
> So you can confirm that for you using "." does work with latest master?

Yes, I cannot reproduce.

**Comment by jannes** [comment]
Couldn't figure out what's wrong yet, but since it seems to be an issue with my setup I'll close this issue. Thanks for your help :)

**Comment by ggandor** [comment]
Sanity check: put a print statement below this line in the source, and do an operation with leap:

https://github.com/ggandor/leap.nvim/blob/87d206bf678451301fa2de993db286c136cf383b/lua/leap/main.lua#L37

**Comment by istrupin** [comment]
@jannes I'm having an identical issue -- did you ever find a fix?
