### ISSUE TITLE
Cursor Not Moving with s{char}{label} in init.vim Configuration

### ISSUE THREAD

**Issue by Muzzamil1** [ggandor/leap.nvim#219]
Hey there!

First off, huge thanks for creating such an awesome plugin—I'm really enjoying using it!

 I’m trying to get the cursor to move after I press s{char}{label}, and I'm not having any luck. I have tried the setting mentioned here but it's not working. 
 
[Unable to leap to certain single characters](https://github.com/ggandor/leap.nvim/issues/55)
[leap.nvim: 1-char mode (of sorts)](https://www.reddit.com/r/neovim/comments/tvz5zx/leapnvim_1char_mode_of_sorts/)

This is my current init.vim configuration 

```
lua require('leap').add_default_mappings()

 lua << EOF
 require('leap').opts.highlight_unlabeled_phase_one_targets = true
 require('leap').opts.special_keys = {
  next_target = '<enter>',
  prev_target = '<tab>',
  next_group = '<space>',
  prev_group = '<tab>',
  multi_accept = '<enter>',
  multi_revert = '<backspace>',
  next_aot_match= '<enter>',
}
EOF

" lightspeed color theme

" https://github.com/ggandor/leap.nvim/issues/33#issuecomment-1196766168
" highlight LeapBackdrop guifg=#777777

 lua << EOF
vim.api.nvim_set_hl(0, 'LeapBackdrop', { fg='#777777' }) 
vim.api.nvim_set_hl(0, 'LeapMatch', {
  fg = 'white', bold = true, nocombine = true,
})

-- #ccff88 --> leap
-- #f02077 --> lightspeed
vim.api.nvim_set_hl(0, 'LeapLabelPrimary', {
  fg = 'white', bold = true, nocombine = true, bg = '#f02077',
})
vim.api.nvim_set_hl(0, 'LeapLabelSecondary', {
  fg = 'white', bold = true, nocombine = true, bg = '#399d9f',
})
EOF
```

Could you give me some guidance on how to fix this and explain how it works? 

Thanks a lot!

**Comment by ggandor** [comment]
> First off, huge thanks for creating such an awesome plugin—I'm really enjoying using it!

Thank you :)

> I’m trying to get the cursor to move after I press s{char}{label}, and I'm not having any luck

You cannot do `s{char}{label}` (if you want something like that, check flit.nvim), however, you can `s{char}<enter>...`, which jumps to the first match, and then can visit each one on subsequent presses of `<enter>`. See `:help leap-traversal`. Also, you have lots of deprecated stuff in your config, I recommend having look at the current docs.

**Comment by Muzzamil1** [comment]
Thanks for the suggestions! I'll check out flit.nvim. Also, I'll review my config for deprecated elements and update accordingly. Appreciate the help!
