### ISSUE TITLE
Show label at first match char

### ISSUE THREAD

**Issue by xzbdmw** [ggandor/leap.nvim#220]
I found displaying label in the third character is not intuitive to me. When you press label to jump, cursor actually jumps to the first typed char, ideally, put label at first match position is better?

**Comment by ggandor** [comment]
https://github.com/ggandor/leap.nvim/discussions/140

**Comment by xzbdmw** [comment]
@ggandor Hi after two month of use I still can't get used to that highlighted label is not the one my cursor will be after a jump, could you add an option for that, is it trivial?

**Comment by ggandor** [comment]
I think I actually agree that this could be added as an option.

**Comment by abeldekat** [comment]
I also would like to have this option for the same reasons [specified](https://github.com/ggandor/leap.nvim/issues/220#issuecomment-2143696674) by @xzbdmw.

Recently `opts.max_phase_one_targets` has been [removed](https://github.com/ggandor/leap.nvim/commit/9958013bd9c41e6f32af0202b9ea41055fe4667e).
