### ISSUE TITLE
<CR> after the auto jump results in additional movement

### ISSUE THREAD

**Issue by awerebea** [ggandor/leap.nvim#227]
Pressing the \<CR\> key, being in the position of the nearest search match after the auto jump, leads to the execution of `rhs` from the `n` mode key combination for \<CR\>.
Is it possible instead to just confirm the current target and complete the leap?
Do not treat \<CR\> as a `safe_label` may be?

**Comment by ggandor** [comment]
`special_keys.next_target` is set to `enter` by default (`:help leap-traversal`).

**Comment by awerebea** [comment]
Hi, thank you for fast response!

I read the documentation and tried to add `require("leap").opts.special_keys.next_target="<tab>"` to the configuration.
But still, if I press \<CR\> right after autojump, I get an additional move to the next line.
Or, since I use [wildfire.nvim](https://github.com/SUSTech-data/wildfire.nvim), I get the TreeSitter node under the cursor to be selected, which is frankly very annoying to be honest.
I would like to always just end the leap with \<enter\>, is it possible to implement this?
Or does it behave differently in your setup?

**Comment by ggandor** [comment]
The point of autojump and using safe labels is that you _don't_ have to accept the match. If you press `enter`, that's already the normal `enter` behavior (moving a line downward).

https://github.com/ggandor/leap.nvim/blob/b1ecfb63c0b8babfd0dcd6b5ca6de37bbf3526cd/doc/leap.txt#L38-L41
