### ISSUE TITLE
Errors with custom highlights

### ISSUE THREAD

**Issue by Suyashtnt** [ggandor/leap.nvim#23]
I'm adding intergration into the catppuccin plugin, but when enabling the custom highlights, using leap fails

Highlights: https://github.com/Suyashtnt/nvim-1/blob/feature/leap/lua/catppuccin/core/integrations/leap.lua#L30-L35

![image](https://user-images.githubusercontent.com/45307955/175373085-b16a8233-9c1b-4486-85da-73a89d320a3d.png)

**Comment by ggandor** [comment]
Thanks very much for reporting!
