### ISSUE TITLE
Backdrop dimming works on `<Plug>(leap-backward)` but not `<Plug>(leap-forward)`

### ISSUE THREAD

**Issue by mawkler** [ggandor/leap.nvim#233]
I only get the backdrop dimming when I do `<Plug>(leap-backward)`. When doing `<Plug>(leap-forward)` there's no dimming.

To reproduce:

2. Use the following config:
   <details>
   <summary><b>Click to expand</b></summary>

   ```lua
   local lazypath = vim.fn.stdpath('data') .. '/lazy/lazy.nvim'
   if not vim.loop.fs_stat(lazypath) then
     vim.fn.system({
       'git',
       'clone',
       '--filter=blob:none',
       'https://github.com/folke/lazy.nvim.git',
       '--branch=stable', -- latest stable release
       lazypath,
     })
   end
   vim.opt.rtp:prepend(lazypath)

   vim.api.nvim_set_hl(0, 'LeapBackdrop', { link = 'Comment' })

   require('lazy').setup({
     {
       'ggandor/leap.nvim',
       dependencies = 'tpope/vim-repeat',
       keys = {
         { 's', '<Plug>(leap-forward)',  mode = { 'n', 'x', 'o' }, desc = 'Leap downwards' },
         { 'S', '<Plug>(leap-backward)', mode = { 'n', 'x', 'o' }, desc = 'Leap upwards' },
       },
       opts = {}
     }
   })
   ```

   </details>

1. `nvim -u path/to/config/above some-file-with-a-couple-lines`
1. `M` (just to put the cursor in the middle of the screen)
1. `S` dims everything above cursor
1. `s` **doesn't** dim everything below cursor

**Comment by ggandor** [comment]
I cannot reproduce with the above config. Backdrop works with `s` too.

Note: no need to use `keys` (https://github.com/ggandor/leap.nvim/issues/191; https://github.com/ggandor/leap.nvim?tab=readme-ov-file#installation -> "Lazy loading")

**Comment by mawkler** [comment]
I was on a Neovim nightly build from a few weeks ago. The error doesn't appear on 0.10.

Now I also tried upgrading to the latest nightly build, and the issue seems to have disappeared.

**Comment by ALVAROPING1** [comment]
Encountered this issue on 0.10 while testing different configs. After a while i noticed that sometimes the backdrop did work, and with further testing it seems like it happens when the cursor is at the last line of the buffer

https://github.com/ggandor/leap.nvim/assets/43814863/572d4938-c460-4516-8f5b-57e307cdcfe7
