### ISSUE TITLE
Be able to add exclusions for characters used for labels or never use `s`

### ISSUE THREAD

**Issue by hboon** [ggandor/leap.nvim#235]
I customize the keymappings and use `f` and `F` to move forward and backward:

```
vim.keymap.set({'n', 'x', 'o'}, 'f',  '<Plug>(leap-forward)')
vim.keymap.set({'n', 'x', 'o'}, 'F',  '<Plug>(leap-backward)')
```

The labels include `s`. So after entering the second character, if I type `s` (to trigger the default vim behavior to delete one character and enter insert mode immediately), it jumps.

**Comment by ggandor** [comment]
`require('leap').opts.safe_labels = ...` (`:help leap-config`)
