### ISSUE TITLE
Support letter case

### ISSUE THREAD

**Issue by mangelozzi** [ggandor/leap.nvim#238]
I just installed this plugin and giving it a while, it looks very promising in terms of productivity, no more vim golf!

I understand there have been a lot of issue raised about smart case. But how about a simple respect the letter case option?

I often find myself typing the letter case but it does not help narrow down the options at all. If the person enabled respect latter case, then the upper and lower case versions of the same letter are treated as two different chars, simple and deterministic.
The user commits to typing the correct case for enhanced reduction.

## Side Note
PS wrt to smart case, I dont understand why it can't be implemented for just the first char, it's like that issue with the one way alias, where 'A' is an alias for 'a', but 'a' is not an alias for 'A'. It makes the initial letter a better hit, most of the time one is search for title or camelcased words when using a capital, so if the 2nd letter is case independant is largely irrelevant.

Cheers!

**Comment by ggandor** [comment]
`require('leap').opts.case_sensitive = true` ;)

> I dont understand why it can't be implemented for just the first char

Possible of course, but it would be pretty surprising behavior, and would need extra documentation. I might experiment with it.

**Comment by mangelozzi** [comment]
Great thank you!
Where is this option documented? I did check the readme a few times to make sure I'm not missing anything:
<https://github.com/ggandor/leap.nvim?tab=readme-ov-file#configuration>

**Comment by ggandor** [comment]
The readme is not comprehensive documentation, `:help leap` is. (https://github.com/ggandor/leap.nvim?tab=readme-ov-file#next-steps)
