### ISSUE TITLE
Bug: `LeapBackdrop` highlight is not fully cleared if `scrolloff` moves window

### ISSUE THREAD

**Issue by sanka047** [ggandor/leap.nvim#25]
Hard to explain this in words, so I'll add some pictures. When I use leap and start typing, it adds the highlight from `LeapBackdrop` to the entire search area. However, I have `vim.opt.scrolloff = 999` in my `init.lua` which causes the window the scroll down when I select the right entry.

#### Starting search: `squ`
<img width="500" alt="Screen Shot 2022-06-26 at 7 18 53 PM" src="https://user-images.githubusercontent.com/50463858/175839839-80506b7c-a4ef-48bc-81de-1e25993a498e.png">

#### Pick entry: `d`
<img width="500" alt="Screen Shot 2022-06-26 at 7 21 30 PM" src="https://user-images.githubusercontent.com/50463858/175839943-a3667a96-6d60-4f59-ab76-0b7794e5a6d1.png">

#### Scroll back to top: `gg`
<img width="500" alt="Screen Shot 2022-06-26 at 7 22 43 PM" src="https://user-images.githubusercontent.com/50463858/175839996-9a76fd1f-d367-49cc-8f9b-59891984e186.png">

Hope that makes the issue clear! Seemingly, there is an issue with highlight removal when it scrolls during the jump. I'm not quite sure how `neovim` handles highlights, but [hop.nvim](https://github.com/phaazon/hop.nvim) doesn't seem to have that problem when using a similar feature, so perhaps their mechanism may shed some light?

Thanks for the help!

**Comment by ggandor** [comment]
I cannot reproduce this. I set scrolloff to 999, executing bidirectional searches, but everything is cleaned up properly. Could you share your Leap config settings and anything else that might be relevant?

**Comment by sanka047** [comment]
I tried with bidirectional searches and it worked fine as well. Try the default `Plug` mappings?

https://github.com/sanka047/dotfiles/blob/main/nvim/lua/sanka047/plugins/nav/leap.lua

**Comment by ggandor** [comment]
In any case, I suggest you try without any of your "magic" config stuff first, just call `leap.set_default_keymaps()`, and see what it does. I see that you have also set custom highlights (not that those should have any effect, but still...)

**Comment by sanka047** [comment]
Yeah, the bidirectional call didn’t mess with the highlighting. There was no bug in that case. It just happens on the forward and backward calls.

Tried the default keymaps with no luck. Still results in the highlight problem.

**Comment by sanka047** [comment]
At work at the moment, but I’ll attempt removing all other plugins and see if it’s some weird interaction in the evening

**Comment by sanka047** [comment]
To clarify, the bug only happens if the section scrolls *off screen* after the jump. So in the pictures, that greyed out section was the section that `scrolloff ` scrolled past
