### ISSUE TITLE
labels aren't highlighted in certain colorscheme

### ISSUE THREAD

**Issue by csessh** [ggandor/leap.nvim#250]
Take this example: 
I typed `sop`, leaping to opt. as you can see, the search area is greyed out, but the markers/labels aren't highlighted. 

![Screenshot from 2024-10-10 17-45-07](https://github.com/user-attachments/assets/01b029ce-a8c5-4e57-8f23-955d67ac50b9)

This is `eldritch` theme. It works just fine for most other schemes I've tried so far: `bamboo`, `cyberdream` ... 

Is there an option to configure label color?

**Comment by csessh** [comment]
Never mind. 
I found what I'm after in the vimdoc.

**Comment by raine** [comment]
@csessh How did you end up fixing them? I'm puzzled because the leap default highlights used to work in my theme (iceberg.vim) and all of a sudden without updating anything, they don't anymore.

**Comment by csessh** [comment]
I haven't got a change to fix it yet.
I thought I'd circle back to it in the next couple of days.

**Comment by csessh** [comment]
>  without updating anything, they don't anymore. 

I was suspecting one of the plugins as I ran lazy update prior to noticing this issue.

Reopen this one?

**Comment by raine** [comment]
I tested another colorscheme, tokyonight, that defines highlights for leap and it works there.

Also tested overriding the highlights manually with:

```lua
-- works
vim.api.nvim_set_hl(0, 'LeapBackdrop', { link = 'Comment' })
-- does not work
vim.api.nvim_set_hl(0, 'LeapMatch', {
  fg = 'red', bold = true, nocombine = true,
})
```

The `LeapBackdrop` one works, but `LeapMatch` does not do anything.

I wonder how the `LeapMatch` highlight group would break.

**Comment by ggandor** [comment]
Might be related to https://github.com/ggandor/leap.nvim/issues/18#issuecomment-2209493654, but `LeapLabelPrimary` should still work, and `LeapMatch` has not been touched...

**Comment by jonaz** [comment]
My default also stopped working. 
LeapLabelPrimary xxx links to IncSearch
LeapLabel      xxx cleared

But LeapLabel seems to take priority. 

So if i set LeapLabel to IncSearch it works for me. 
`hi def link LeapLabel IncSearch` 

But i guess the default should set both LeapLabelPrimary and LeapLabel to the same?

**Comment by csessh** [comment]
@jonaz That works for me. Thanks heaps

```
    {
        "eldritch-theme/eldritch.nvim",
        lazy = true,
        priority = 1000,
        config = function()
            vim.cmd "hi def link LeapLabel IncSearch"
        end,
    },
```
