### ISSUE TITLE
Empty match labels

### ISSUE THREAD

**Issue by korchizhinskiy** [ggandor/leap.nvim#251]
When I found by letter ("L" in example), I get some jumps and any empty labels (see on screen). What I do wrong? I using default config.
![image](https://github.com/user-attachments/assets/e9f0133d-6985-45f9-8b02-688aeb03ed22)

**Comment by korchizhinskiy** [comment]
But if i move below, i get mathes in this plases, seems to lack the characters to display, although it should show `leap.opts.labels`
![image](https://github.com/user-attachments/assets/ac16d5ab-6df0-4e73-badb-7397c8d89027)

**Comment by ggandor** [comment]
If there are more matches than available labels (first screenshot), you can use `<space>`/`<backspace>` to switch between groups. See the docs: `:help leap-usage`, `:help leap-concealed-labels`.
