### ISSUE TITLE
nvim 0.7.2

### ISSUE THREAD

**Issue by desdic** [ggandor/leap.nvim#26]
I can see that this was supposed to work with 0.7+ but it also states that nightly should be used. I tried with 0.7.2 but it does highlight the works but dosn't jump .. you just get an error with

not found: w

if I press sw for finding a word starting with w .. is it supposed to work with 0.7 or only nightly ?

**Comment by ggandor** [comment]
Yeah, generally we follow the nightly, but in practice, at the moment Leap should work even on 0.7.0 (it works for me), so the issue is something else.

Can you give a full reproducible example (window content & command sequence)?

**Comment by desdic** [comment]
oh I think I found the issue .. look at the screenshot .. it does work but  .. when hitting s and then h it highlights different chars then the one I need to press. Pressing shi gives me `highlight_ahead_of_time` but the sh highligts like in the image

![2022-06-27_190401_227277435](https://user-images.githubusercontent.com/13243026/175996717-66a8cee4-5b6d-45c7-886f-3c5f7a966636.png)

**Comment by ggandor** [comment]
It should look exactly like the screenshot after entering `sh`... Maybe something is not clear about the usage then? (Make sure to read through the example in the Readme first.)

**Comment by desdic** [comment]
yes maybe its because I'm comparing to something like hop .. I'll close it since the error is on my part :) and thanks for the quick response
