### ISSUE TITLE
Support smartcase

### ISSUE THREAD

**Issue by romgrk** [ggandor/leap.nvim#28]
It would be nice if the plugin implemented smartcase: if there is an uppercase letter in the input, use case-sensitive search; otherwise, use case-insensitive search.

**Comment by ggandor** [comment]
It is impossible, unfortunately. It would work for the first input character, but not for the second. We should decide on the label ahead of time. If you enter an uppercase character that means you usually get a shorter "route" to the target (that is, a different label) than if you'd enter the lowercase one (this would be the point of smartcase, after all). See also: https://github.com/ggandor/lightspeed.nvim/issues/64.

**Comment by ggandor** [comment]
While you're here: https://github.com/ggandor/leap.nvim/issues/29. Any thoughts/comments? Is that trivial/tricky? Anything to pay attention to? (Should be doable, since those are just windows, not actual folds.)
