### ISSUE TITLE
other entry key than `s/S`

### ISSUE THREAD

**Issue by matu3ba** [ggandor/leap.nvim#30]
Will there be an option to remap (dynamically) the keys `s/S` ?
My main use case is https://github.com/kylechui/nvim-surround.

I checked https://github.com/ggandor/leap.nvim/blob/1d1032feefb53d407c59ea37d80374d77f6f9f3b/doc/leap.txt and did not find any functionality to rebind it/overwrite the default.

Since I dont need the plugin extremely frequent, I would like to use `_/-` instead or (eventually) hydra.nvim (https://github.com/anuvyklack/hydra.nvim).

**Comment by ggandor** [comment]
`:help leap-custom-keymaps`? `vim.keymap.set('n', '_', '<Plug>(leap-forward)', {})`, etc.

**Comment by avborup** [comment]
Is there a way to achieve this that doesn't depend on Plug? Can I change this keymap using packer?

**Comment by ggandor** [comment]
@avborup  `<Plug>` has nothing to do with vim-plug, it is a native Vim feature to alias right hand sides of mappings, see `:help <Plug>`. (Bottom line: you don't have to do anything.)

**Comment by esn89** [comment]
Hi all, I am having some issues with this.  Currently, I am trying to re-map the visual/visual-block mode of this to use something different like `-` or `_`:

I have this in my plugin set up:

```lua
{
        'ggandor/leap.nvim',
        dependencies = {
            'tpope/vim-repeat',
        },
        config = function()
            require('leap').add_default_mappings()
        end,
        keys = {
            { 's', mode = 'n' },
            { 'S', mode = 'n' },
            { 'f', mode = 'n' },
            { 'F', mode = 'n' },
            { 't', mode = 'n' },
            { 'T', mode = 'n' },
            { 'f', mode = 'v' },
            { 'F', mode = 'v' },
            { 't', mode = 'v' },
            { 'T', mode = 'v' },
            { '-', mode = 'v' },
            { '_', mode = 'v' },
        },
    }
 ```
 
 And in my init.lua:
 
 ```lua
 vim.keymap.set({ 'v' }, '-', '<Plug>(leap-forward)', {})
vim.keymap.set({ 'v' }, '_', '<Plug>(leap-backward)', {})
```

However, once I do a visual-block mode, pressing hyphen does not give the intended behaviour of leaping forward.

**Comment by ggandor** [comment]
The problem might be `keys`, no need for that: https://github.com/ggandor/leap.nvim/issues/191.

**Comment by esn89** [comment]
This seems to have fixed it.  Thanks @ggandor
