### ISSUE TITLE
This plugin is awesome

### ISSUE THREAD

**Issue by romgrk** [ggandor/leap.nvim#32]
Hi,

I just wanted to say that my motions across the screen have never felt as fast and natural as they have with this plugin. Thank you so much for building it, you have my eternal gratitude.

This issue can be closed.

**Comment by ziontee113** [comment]
Yeah, I just installed it and it can see targets behind conceals. It's awesome!

**Comment by ggandor** [comment]
@romgrk Thank you very much, this feels really good, especially coming from a fellow author with a record like yours (similar gratitudes for treesitter-context)!

**Comment by ggandor** [comment]
@ziontee113 Now that you mention conceals, I'm not sure that is a feature (it is just simpler implementation-wise). The most intuitive/useful behaviour would be to ignore concealed characters, and search as if the concealed view would be the actual buffer state. Don't you think so?

**Comment by ziontee113** [comment]
@ggandor that'd be cool, I think you just need to give the User the option to toggle it ;)

I find leap able to jump to concealed targets to be very useful, just give the User the option and it'll be great!

**Comment by romgrk** [comment]
Please discuss in a different issue. This issue is reserved for my gratitude. Thanks again @ggandor. :star2:

**Comment by ggandor** [comment]
Roger that, thanks again for the small dopamine hit 🙂
