### ISSUE TITLE
Dimming the text

### ISSUE THREAD

**Issue by augustocdias** [ggandor/leap.nvim#33]
I'm moving from lightspeed to leap and so far it feels great. The only thing I miss from lightspeed was the dimming of the text that was being searched. For me personally was very helpful to see only the matches from lightspeed with the colorscheme "disabled".

**Comment by ggandor** [comment]
You can set the `LeapBackdrop` highlight group, e.g. `:highlight LeapBackdrop guifg=#777777`. As Leap by default only uses "boxed" labels having their own background color, there's less need for such dimming.

**Comment by Armadillidiid** [comment]
> You can set the `LeapBackdrop` highlight group, e.g. `:highlight LeapBackdrop guifg=#777777`. As Leap by default only uses "boxed" labels having their own background color, there's less need for such dimming.

How do I set the `LeapLabelSelected`? I've tried `:highlight LeapLabelSelected guibg=Magenta` but the color of labels doesn't change.
