### ISSUE TITLE
Error attempt to index field 'wininfo' (a nil value)

### ISSUE THREAD

**Issue by Shatur** [ggandor/leap.nvim#34]
**Steps to reproduce**

1. Execute command `:lua require('leap').leap({multiselect = true})`
2. Make a few matches.
3. `<CR>`.

**Expected behavior**

I able to execute commands on cursors.

**Actual behavior**

```
E5108: Error executing lua ...nfig/nvim/pack/plugins/start/leap.nvim/lua/leap/main.lua:594: attempt to index field 'wininfo' (a nil value)
stack traceback:
	...nfig/nvim/pack/plugins/start/leap.nvim/lua/leap/main.lua:594: in function 'do_action'
 	...nfig/nvim/pack/plugins/start/leap.nvim/lua/leap/main.lua:984: in function 'leap'
 	[string ":lua"]:1: in main chunk
```

**Comment by ggandor** [comment]
The problem is that `multiselect` assumes the user provides a custom `action` callback too. If there's no `action`, it defaults to the native "jump" function, which obviously makes no sense for `multiselect`.

**Comment by Shatur** [comment]
Oh, got it, thanks!
