### ISSUE TITLE
Export <Plug> functions

### ISSUE THREAD

**Issue by Shatur** [ggandor/leap.nvim#35]
The plugin provides [Plug mappings](https://github.com/ggandor/leap.nvim/blob/main/plugin/init.lua). But it would be nice to export the functions too to be able to map them using vim.keymap.

To map `leap.leap()` function with `vim.keymap` I have to do something like this:

```lua
local function leap_forward()
  leap.leap({})
end

local function leap_forward_x()
  leap.leap({ offset = 1, inclusive_op = true })
end

vim.keymap.set({ 'n', 'x' }, 'f', leap_forward, { noremap = true })
vim.keymap.set({ 'n', 'x' }, 'F', leap_backward, { noremap = true })
```

or use `<Plug>` mappings. But it would be nice to have functions that used in `<Plug>` mappings exported directly:

```lua
local leap = require('leap')
vim.keymap.set({ 'n', 'x' }, leap.leap_forward, r, { noremap = true })
vim.keymap.set({ 'n', 'x' }, 'F', leap.leap_backward, { noremap = true })
```

And re-use this functions for [Plug](https://github.com/ggandor/leap.nvim/blob/main/plugin/init.lua) mappings.

**Comment by ggandor** [comment]
There is no problem here, you can use `<Plug>` keys as RHS with `vim.keymap.set` (just like with `api.nvim_set_keymap`). If you use `vim.keymap.set`, you don't even have to specify `noremap = true`. By default, it assumes `noremap=false` if there is a `<Plug>` key in the LHS (as those are recursive by nature), and otherwise `noremap=true`.

So it's as easy as `vim.keymap.set({'n', 'x'}, 'f', '<Plug>(leap-forward)')`.

**Comment by Shatur** [comment]
> There is no problem here, you can use <Plug> keys as RHS with vim.keymap.set (just like with api.nvim_set_keymap). 

Sure, I know it, but mapping functions directly is a more Neovim way. `<Plug>` is more a Vim thing. This is why I asked to export the functions you use for `<Plug>`.

**Comment by ggandor** [comment]
Oh, I missed the

> or use <Plug> mappings

part, sorry for the lecture :)

> <Plug> is more a Vim thing

In what sense? `<Plug>` will not go anywhere as it's a general mechanism, and could be used for many other things besides aliasing function calls. (Sidenote: This is a bit similar to the strange kind of OCD of Neovimmers who "don't want touch Vimscript plugins, by principle", even if said plugin is, say, 200 LOC, complete, robust, bug-free, works _perfectly fine_, and performance considerations in its case are totally irrelevant... :P) Bottom line: request noted, but I don't see any practical purpose of exposing those calls in another wrapping layer, just for the heck of it.

**Comment by Shatur** [comment]
No practical reason, it just looks a little nicer as for my taste in config:

```lua
local leap = require('leap')
vim.keymap.set({ 'n', 'x' }, leap.leap_forward, { noremap = true })
vim.keymap.set({ 'n', 'x' }, 'F', leap.leap_backward, { noremap = true })

vim.keymap.set({ 'n', 'x' }, '<Plug>leap-forward', { noremap = true })
vim.keymap.set({ 'n', 'x' }, 'F', '<Plug>leap-backward', { noremap = true })
```

**Comment by ggandor** [comment]
Both are fine for our purposes, obviously. But as the `<Plug>` keys are already there, they will stay, and it would be absurd to add a redundant form to provide "aesthetic variety". We could deprecate the `<Plug>` keys, but I'm not sure it would worth the trouble.

**Comment by Shatur** [comment]
Yes, you are right, better to keep it as is.

**Comment by ggandor** [comment]
Notes to myself (too), for future reference:
- `<Plug>` keys can be overloaded on different modes, having the same name. For example, `forward-x` would need a different `offset` in Visual and Operator-pending mode if we wouldn't have implemented an `inclusive_op` flag.
- Using `<Plug>`, you don't need a line aliasing `local leap = require('leap')`, or equivalently, put `require('leap')` in every `keymap` line, if you only want to set keymaps in your config, and nothing else.
