### ISSUE TITLE
Some magic causes vim to be blocked

### ISSUE THREAD

**Issue by name-snrl** [ggandor/leap.nvim#44]
Hi, great plugin, thank you.

Before 054456aa7fa6ddbee23b6ee6d50ad9086c9d78cc plugin worked well. Now when certain conditions are met (about them below) and you call `:lua require('leap').leap { inclusive_op = true }` it blocks vim. This is very similar to recursion because vim starts to consume too much CPU.

Specs:
- Nixos Unstable
- alacritty 0.10.1
- sway 1.7
- neovim v0.8.0-dev. I can't tell you which commit it is, sorry. If it's important, I can build neovim with any commit.

To reproduce:
1. put this line in file `дальнейшего сохранения, так же как и с гитом - к ним можно откатываться`
2. `nvim --clean path/to/file`
3. shrink the terminal window to 82 or less characters
4. `:set nowrap`
5. `:set rtp+=path/to/plugin`
6. `lua require('leap').leap { inclusive_op = true }`
7. press `-`

https://user-images.githubusercontent.com/72071763/187273795-f15d1738-66eb-4269-810e-c1ed9f81a0cb.mp4

error:
```
E5108: Error executing lua Keyboard interrupt
stack traceback:
        [C]: in function 'searchpos'
        ...im/site/pack/packer/start/leap.nvim//lua/leap/search.lua:165: in function '(for generator)'
        ...im/site/pack/packer/start/leap.nvim//lua/leap/search.lua:229: in function '_197_'
        ...nvim/site/pack/packer/start/leap.nvim//lua/leap/main.lua:1125: in function 'leap'
        [string ":lua"]:1: in main chunk
```
It is pure magic to me, but maybe you can fix it.

**Comment by ggandor** [comment]
Thanks very much for reporting! I found and fixed a bunch of related bugs.
