### ISSUE TITLE
Leap (probably) OK with  vscode-neovim / vscode-neovim?

### ISSUE THREAD

**Issue by proofer** [ggandor/leap.nvim#45]
The subject repo is for a Visual Studio Code extension that embeds a NeoVim instance. Its  Wiki says, "The problem with [easymotion] is that it replaces your text with markers and then restores [it]. ... [F]or VS Code it leads to broken text and many errors reported while you're jumping. [So] @asvetliakov created the special [vim-easymotion fork](https://github.com/asvetliakov/vim-easymotion). This version of the plugin doesn't touch your text ... ."

In this respect should Leap be OK with respect to VS Code?

(I haven't tried Leap yet. The README is daunting -- so many details -- but I think it's likely to be made clear by use. I'd  like it to work with VSCode, though.) Thanks for tolerating a newbie question!

**Comment by ggandor** [comment]
Leap uses so called "extmarks", a new feature of Neovim, so it doesn't modify the text content at all, it works fine with VSCode.

> The README is daunting

That doesn't sound good... do you have any suggestions for improvements maybe (what is missing, what should be mentioned/explained earlier, or in a more concise fashion)?

**Comment by proofer** [comment]
Thanks for the good news re: VSCode! Not too long after my initial issue post, I installed Leap and spent a some time using it. I was right: its use is straightforward -- or, at least, its primary use as a two-character target selector is.

My initial reaction to the README was that it's long. (Might be your initial reaction to this comment!) This doesn't imply **_too_** long. But being occasionally prudent, I felt I had to read it all before installing it.  My half-baked idea is that it could benefit from better separation of usage info from comparative market analysis and design strategy. NB I'm pretty new to (Neo)Vim and haven't used a similar product unless you count the built-in "f", "t", "F", "T".

Perhaps rename Introduction to Rationale and move it down. The first thing I want to know is: what does this plugin **_do_**.

As to usage: the TL;DR could be shortened by just describing the "standard" two-character use and not mixing in traversal mode. But then describe traversal mode right under that. Also, I don't understand what the four "#"-designated numbers refer to. This might relate to my not at all being able to follow the animated illustration underneath.

Detail: "For the moment, [repeat.vim](https://github.com/tpope/vim-repeat) is required for the dot-repeat functionality to work as intended." Maybe because I'm pretty new to (Neo)Vim I don't understand what this refers to. AFAIK "." repeats the most recent **_change_** to the text, and Leap doesn't make changes. So, what is intended?

I appreciate all the work, including the complete user manual in :help as well as the extensibility, even though I don't have any immediate use plans for the latter. I've decided to keep Leap installed and expect to use it frequently.

**Comment by ggandor** [comment]
Thank you for the detailed response, this is very helpful, I might very well apply some of the suggestions!

Regarding dot-repeat: operators take a selection (motion or text object) as argument, e.g. `yw`. Leap motions can be given as arguments to operators (e.g. `yz{char1}{char2}{some-label}`) just as well, but repeating those operations with `.` doesn't work out of the box, since from Neovim's perspective a Leap motion is just a "black box" function call that ultimately moves the cursor to somewhere. That is, Neovim by itself cannot replay the exact sequence with the input pattern and the label selection, and that's why plugins like Leap need to set the dot-repeat behaviour "manually".
