### ISSUE TITLE
Leap is not triggered with s & S

### ISSUE THREAD

**Issue by stefanfrede** [ggandor/leap.nvim#46]
After installing Leap it is not triggered if I press `s` or `S`.

Instead `s` removes a space and `S` the whole line.

It worked once (no clue why) but after I restarted my terminal I was stuck again with the behaviour I described above.

Lightspeed is working as expected.

**Comment by ggandor** [comment]
Leap doesn't set keymaps by default (as opposed to Lightspeed). You have to explicitly call `require('leap').set_default_keymaps()`.

**Comment by stefanfrede** [comment]
That did the trick. Thank you!
