### ISSUE TITLE
[Feature Request]need a cross-all-window option

### ISSUE THREAD

**Issue by Cicero24C** [ggandor/leap.nvim#49]
The existing `cross-window motions` can only search in **other** windows on the tab page, I want a `cross-all-window` motion which include current window. I'm used to getting anywhere with one key, I don't want to check whether it is forward or backward, nor whether it is the other window or just the current window.

**Comment by ggandor** [comment]
It is possible, see the example for `target_windows` at https://github.com/ggandor/leap.nvim#calling-leap-with-custom-arguments. `<Plug>` keys are only defined for the default motion set, otherwise we could define arbitrarily many of them.
