### ISSUE TITLE
equivalence_classes not working anymore

### ISSUE THREAD

**Issue by Baehn** [ggandor/leap.nvim#53]
setting following does not work anymore after update

```
require("leap").setup {
	equivalence_classes = { '({[', ')}]' },
}
```

**Comment by Baehn** [comment]
the problematic commit is "c6b501c", before this its working fine
(thank you for your great plugin btw :)

**Comment by ggandor** [comment]
Thanks, good catch! In fact, the whole `setup` function was broken.
