### ISSUE TITLE
Unlabeled pattern not highlighting do not work.

### ISSUE THREAD

**Issue by ameddin73** [ggandor/leap.nvim#54]
### Neovim version (nvim -v)
NVIM v0.7.2
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@HMBRW-A-001-M1-005.local

Configured with Lunarvim

### Operating system/version
macOS Montery 12.6

### Terminal name/version
xterm-256color

### Installation
Packer: `{ "ggandor/leap.nvim" }`
Config: `require("leap").set_default_keymaps(true)`

### Expected behavior
Open [example file](https://github.com/neovim/neovim/blob/8215c05945054755b2c3cadae198894372dbfe0f/src/nvim/window.c#L1078) in Neovim and hit `s` and `o` in normal mode. Expect to see green colored text with underlines for matches.
![image](https://user-images.githubusercontent.com/6893820/193613126-72c69184-a30d-4bad-8b49-fc9718bb4fc5.png)

### Actual behavior
Open [example file](https://github.com/neovim/neovim/blob/8215c05945054755b2c3cadae198894372dbfe0f/src/nvim/window.c#L1078) in Neovim and hit `s` and `o` in normal mode. Only see match groups.
![Screen Shot 2022-10-03 at 8 06 07 AM](https://user-images.githubusercontent.com/6893820/193614021-771dbb87-849f-4ac2-b832-3faa0f9f181e.png)

Also
![Screen Shot 2022-10-03 at 8 26 28 AM](https://user-images.githubusercontent.com/6893820/193616102-f19416fc-2ba5-43f4-9502-34e418f5fec3.png)

continue pattern with `soh` and get error.
![Screen Shot 2022-10-03 at 8 19 35 AM](https://user-images.githubusercontent.com/6893820/193615895-b0dc5705-65c0-4327-ab84-456a2e3303c6.png)

### What I tried
- Resetting to default colorscheme
- Overriding `LeapMatch` highlights group to be an obvious style (no change)
- Setting `LeapBackdrop` to dark grey (this sets it to grey successfully but does not fix the main issue)
- Reinstalling Leap.nvim

I think this plugin is really, really cool and I'm so excited to try it! It feels like the last important thing I need to finally cut the cord from my IDE. Thanks so much for developing it, and I appreciate any help you can offer for this issue!

**Comment by ggandor** [comment]
Highlighting the matches themselves is opt-in. On the screenshots it is switched on, but it's actually redundant, so it's not enabled by default (the exception is [when a match covers a label](https://github.com/ggandor/leap.nvim/tree/5a09c30bf676d1392ff00eb9a41e0a1fc9b60a1b#resolving-highlighting-conflicts-in-the-first-phase), then the highlight is enforced). You can turn it on by setting: `require('leap').opts.highlight_unlabeled = true`. (This option will probably be renamed in the near future to `highlight_unlabeled_aot_targets` or something like that, so don't be surprised.)

> I think this plugin is really, really cool and I'm so excited to try it! It feels like the last important thing I need to finally cut the cord from my IDE.

Thank you, this sounds great!

**Comment by ameddin73** [comment]
Thanks, sorry I didn't see that earlier. Working great!
