### ISSUE TITLE
Unable to leap to certain single characters

### ISSUE THREAD

**Issue by sQVe** [ggandor/leap.nvim#55]
Hey 👋,

I noted today that I'm no longer able to leap to certain single characters. This have previously worked by pressing next match.

This is the sequence I can replace it on:
- Press <kbd>s</kbd>
- Press <kbd>i</kbd> (the character you want to leap to)
- Press <kbd>Enter</kbd> (or the key you have set to next match)

It then outputs `not found: i` instead of allowing me to move to the next match. Do note that I only see this issue for certain characters, leaping to `e` works perfectly for examples.

I'd love some assistance debugging this if it's only an issue on my side... Also, thank you for an fantastic plugin. ❤️

**Comment by ggandor** [comment]
Very interesting, I cannot reproduce. Any special config settings?

**Comment by sQVe** [comment]
@ggandor Super weird that you cannot replicate it 🤔 

I can replicate it with the following minimal config:

```lua
-- this template is borrowed from nvim-lspconfig
local on_windows = vim.loop.os_uname().version:match("Windows")

local function join_paths(...)
	local path_sep = on_windows and "\\" or "/"
	local result = table.concat({ ... }, path_sep)
	return result
end

vim.g.loaded_remote_plugins = ""
vim.cmd([[set runtimepath=$VIMRUNTIME]])

local temp_dir = vim.loop.os_getenv("TEMP") or "/tmp"

vim.cmd("set packpath=" .. join_paths(temp_dir, "nvim", "site"))

local package_root = join_paths(temp_dir, "nvim", "site", "pack")
local install_path = join_paths(package_root, "packer", "start", "packer.nvim")
local compile_path = join_paths(install_path, "plugin", "packer_compiled.lua")

local function load_plugins()
	-- only add other plugins if they are necessary to reproduce the issue
	require("packer").startup({
		{
			"wbthomason/packer.nvim",
			{
				"ggandor/leap.nvim", -- Quick jump.
				config = function()
					local leap = require("leap")

					leap.set_default_keymaps()
					leap.setup({
						highlight_ahead_of_time = false,
						special_keys = {
							repeat_search = "<CR>",
							next_match = "<CR>",
							prev_match = "<S-CR>",
							next_group = "<Tab>",
							prev_group = "<S-Tab>",
							eol = "<Space>",
						},
					})
				end,
			},
		},
		config = {
			package_root = package_root,
			compile_path = compile_path,
		},
	})
end

if vim.fn.isdirectory(install_path) == 0 then
	vim.fn.system({ "git", "clone", "https://github.com/wbthomason/packer.nvim", install_path })
	load_plugins()
	require("packer").sync()
else
	load_plugins()
	require("packer").sync()
end
```

If I press <kbd>s</kbd>, <kvd>i<kvd>, <kbd>Enter</kbd>, <kvd>Enter</kbd> my assumption is that it would move me to the second occurrence of `i`, is that  correct`

**Comment by ggandor** [comment]
Ok, I get it. https://github.com/ggandor/leap.nvim/commit/aba53d7a8870426bea89eeca6c3b265d1f94c584 was actually a breaking change (if someone has set custom `special_keys`, then `next_aot_match` is missing now), but I forgot to mention it as such.

**Comment by sQVe** [comment]
@ggandor Great! 

Do I need to do something in regards of `next_aot_match`? I'll fix the deprecated things, thanks for pointing it out 👍🏼

**Comment by ggandor** [comment]
Yeah, you should include `next_aot_match = "<CR>"`, since if you set `special_keys`, that overwrites the whole table, so you should give new values to all fields.

**Comment by ggandor** [comment]
Oops, wait a minute. Note that if you disable two-phase processing (ahead-of-time labels), then, obviously, `next_aot_match` will not work at all, so you lose the ability to `s{char}<cr><cr>...` (as of now).

**Comment by sQVe** [comment]
@ggandor Awesome. Cheers 🍻 I got it working nicely moving back to the defaults but just changing the keymappings.

Closing!
