### ISSUE TITLE
`<Enter>` and `<backspace>` won't work on `multiselect` when `special_keys` is set on `setup()`

### ISSUE THREAD

**Issue by annenpolka** [ggandor/leap.nvim#58]
>  You can revert the most recent pick with `<backspace>`, and accept the selection with `<enter>`.

As the title suggests, when `special_keys` is set on `setup()`, `multiselect` mode's both keybindings `<Enter>` and `<backspace>` won't work.

The same applies if `<enter>` and `<backspace>` are not used for `special_keys`.
I have also confirmed that these work when `special_keys` is not set.

Anyway, thank you for your great plugin!

**Comment by ggandor** [comment]
Oh, right, indeed. In fact, I haven't decided on their names yet, and not documented them, but if you check the [source](https://github.com/ggandor/leap.nvim/blob/937bc9280f0073df16e355887bf5f199cff4ec92/fnl/leap/opts.fnl), you can see that there are the special keys `multi_accept` and `multi_revert` that you can set.
