### ISSUE TITLE
Error when trying to set the default keymaps

### ISSUE THREAD

**Issue by tthkbw** [ggandor/leap.nvim#6]
With 

`require('leap').set_default_keymaps()`

in my init.lua, I get the following error:

```
E5113: Error while calling lua chunk: ...share/nvim/site/pack/packer/start/leap.nvim/lua/leap.lua:1519: attempt to call field 'nvim_create_augroup' (a nil v
alue)
stack traceback:
        ...share/nvim/site/pack/packer/start/leap.nvim/lua/leap.lua:1519: in main chunk
        [C]: in function 'require'
        /Users/tbrown/.config/nvim/init.lua:238: in main chunk
```

since Leap doesn't finish initializing, I can't make anything work. I am running:

NVIM v0.7.0-dev+1129-g30c9c8815
Build type: Release
LuaJIT 2.1.0-beta3

Which is the latest HEAD from homebrew.

macOS 12.3 on a Mac Studio with M1Max.

I have found that this error occurs on non-nightly builds of vim 0.7. Is that my problem? What are my options? Which version to I need?

**Comment by ggandor** [comment]
Yes, you need the very latest nightly release. (I'll update the readme to make it clear.)

**Comment by tthkbw** [comment]
Got it. I now have it working. Thanks for the help.
