### ISSUE TITLE
some ambiguous targets not labelled and don't suppress other actions

### ISSUE THREAD

**Issue by dstoc** [ggandor/leap.nvim#60]
Given the content:
```
test wa wba wbb wbc
```

After `{c1} = w`, the labelling is `test wa wba wb[s] wb[f]` continuing to type `b` then `a` takes me to the corresponding text (`wba`) but also enters insert mode.

**Comment by dstoc** [comment]
I see that setting `safe_labels = {}` disables the auto jump (to `wba` in the above case).

I understand now that having typed the pattern, and based on it not being labelled I should know that the cursor logically there even though it's visible. I'll see how it goes, but I'll probably end up using the above option.

**Comment by ggandor** [comment]
If you don't see the cursor at the target, that is a bug, see #27.
