### ISSUE TITLE
how do you actually use bidirectional?

### ISSUE THREAD

**Issue by ckp95** [ggandor/leap.nvim#61]
Readme says:

```
require('leap').leap { target_windows = { vim.fn.win_getid() } }
```

well, I put that in my config but it still doesn't work. Pressing my keybind just does the same forward / backward search as before. Do I need to bind something different?

this is what I have

```
:lua require('leap').set_default_keymaps()
:lua require('leap').leap { target_windows = { vim.fn.win_getid() } }
:lua vim.api.nvim_set_hl(0, 'LeapBackdrop', { fg = '#707070' })
:lua vim.keymap.set('n', 'f', '<Plug>(leap-forward)', {})
:lua vim.keymap.set('n', 'F', '<Plug>(leap-backward)', {})
```

~~btw also, how do you use the leap as an actual motion for other commands? like with `d` or something.~~ oh wait that's just the "operator pending" mode

**Comment by ggandor** [comment]
That is just the call to `leap` itself, map it to some key (wrapped in a function - see `:help vim.keymap.set`):
```
:lua vim.keymap.set(<modes>, <key>, function () require('leap').leap { target_windows = { vim.fn.win_getid() } } end)
```

**Comment by ckp95** [comment]
Ahh okay. just one other thing, how do I do the same for the operator pending keys? i.e. rebind to something else instead of `z/Z` and `x/X`?

**Comment by ckp95** [comment]
Ah okay thanks. btw what is the reason for having separate keys for forward and backward as default in the first place? I've tried it with bidirectional now, it seems a lot easier to navigate using a single key than having to choose between two.

**Comment by ggandor** [comment]
If the search is directional, we can often jump to the first match automatically, without having to type a label, which is an [awesome feature](https://github.com/ggandor/leap.nvim#smart-autojump). Also, in Visual and Operator-pending mode it makes less sense to use a directionless motion (problems with inclusive/exclusive behaviour, `.`-repeating), and it's better to have a consistent set of motions covering all modes.
