### ISSUE TITLE
How to set highlighted font text color in vscode?

### ISSUE THREAD

**Issue by ericsong** [ggandor/leap.nvim#68]
Thanks for creating this! It was fun to play around with.

Is there a way to set the highlighted font text color to always be a single color? I'm having an issue with vscode+neovim+leap where the highlighted text takes on the color of the character that it's replacing. In some cases, it results in a color that is very hard to distinguish from the highlight background color.

<img width="329" alt="Screen Shot 2022-10-19 at 2 26 33 PM" src="https://user-images.githubusercontent.com/2770197/196776558-daecd9f6-e729-4e14-961c-a79d72dac48e.png">

FWIW, this doesn't seem to be an issue outside of vscode.
<img width="423" alt="Screen Shot 2022-10-19 at 2 40 46 PM" src="https://user-images.githubusercontent.com/2770197/196777232-2462de04-9dfd-47bb-a6f5-b9ca4584a22e.png">

I know the problem probably lies somewhere outside the scope of `leap.nvim` but I was wondering if you had any ideas for what could be worth looking into on the vscode/neovim side.

## Solutions I tried
From https://github.com/ggandor/leap.nvim/issues/15#issuecomment-1207485369
I tried adding this to vscode settings.json but that didn't seem to do anything.
```
"vscode-neovim.highlightGroups.highlights": {
    "Cursor": {
      "backgroundColor": "theme.editor.findMatchBackground",
      "borderColor": "theme.editor.findMatchBorder",
    },
  },
 ```
 --------------

From https://github.com/ggandor/leap.nvim/issues/63#issuecomment-1276254068
Adding `lua vim.api.nvim_set_hl(0, 'LeapLabelPrimary', {ctermfg="White", ctermbg="DarkBlue", bold = true })` to `init.vim`.
Seems to have gotten rid of the highlight background? Didn't fix the font color either.

<img width="312" alt="Screen Shot 2022-10-19 at 2 59 27 PM" src="https://user-images.githubusercontent.com/2770197/196780411-dcb2870a-0289-412f-9e89-d3fd2844f68b.png">

**Comment by ggandor** [comment]
> I was wondering if you had any ideas for what could be worth looking into on the vscode/neovim side

No idea, unfortunately. But I guess the vscode-neovim people can help, you should ask them instead of me :)

**Comment by mendeljacks** [comment]
For me the hilighted text takes the same appearance as the original font which makes it hard to see, did you end up finding a solution to this?
