### ISSUE TITLE
Typo in nvim API call

### ISSUE THREAD

**Issue by CKolkey** [ggandor/leap.nvim#7]
Lines `191`, `194`, and `281` call `api.nvim_exec_autocmds`, but the correct api call is `api.nvim_exec_autocmd`

![Screenshot 2022-04-04 at 15 48 21](https://user-images.githubusercontent.com/7228095/161558231-3879cbe6-8d4a-441d-a43b-d11099e22393.png)

**Comment by CKolkey** [comment]
Apologies, just saw the notice of breaking changes. As you were :)

**Comment by ggandor** [comment]
> As you were :)

Yeah, actually, I did those breaking changes :D
