### ISSUE TITLE
s seems to do nothing sometimes; other times it works as expected

### ISSUE THREAD

**Issue by donhcd** [ggandor/leap.nvim#72]
Hi, I'm having a weird issue trying to use leap. I've installed the plugin with vim-plug and added in the default mappings as advised.

However, sometimes when I open nvim `s` basically gets ignored; e.g. `sce` is equivalent to `ce`, and it will delete from the cursor to the end of the word. Other times (this is hard for me to repro) for some reason it works fine on all files in that nvim session.

I'm not familiar with debugging Vim setups, but I did some googling and I did learn the `:map s` command; in both cases, it has the same output though!
<img width="296" alt="image" src="https://user-images.githubusercontent.com/902007/197851698-57947d6e-8665-4dfa-a280-4df508be9b5a.png">

It feels like it must be some sort of race with how my plugins are getting initialized but I'm not sure how to debug further.

For reference, my neovim config is
```
set runtimepath^=~/.vim runtimepath+=~/.vim/after
let &packpath=&runtimepath
source ~/.vimrc
```
and latest vimrc is https://github.com/donhcd/dotfiles/blob/master/vimrc

thanks for any help!

**Comment by ggandor** [comment]
I just experienced the same issue (for the first time ever).

**Comment by donhcd** [comment]
@ggandor thanks for the reply! I actually haven't been able to repro since I made this ticket. Is there some long-running neovim process outside of running the `nvim` command? (is there a specific command to "restart" neovim?)

At the time I definitely repro'd when running `nvim` multiple times and in different `zsh` instances, but I wonder if maybe restarting my computer fixed this issue. I guess I'm okay closing this issue for now since I'm not sure how to repro again

**Comment by curiousyogurt** [comment]
I have also encountered this issue.  Yesterday (when I first installed Leap), everything worked fine.  Now, it doesn't.  Restarting NeoVim, restarting the Terminal, and restarting the system have made no difference—it still ignores "s".

**Comment by antenando** [comment]
☝️ Exact same thing happened to me today, NVIM v0.9.0

**Comment by ggandor** [comment]
Check whether Leap has been called at all, with the following autocommand:
```lua
vim.api.nvim_create_autocmd('User', { pattern = 'LeapEnter', command = "echo 'Leap is active...' | sleep 500m" })
```

**Comment by ggandor** [comment]
The Leap mapping is defined though, right? (`:nmap s`)

**Comment by ggandor** [comment]
> So we can rule out that this is some kind of internal problem

One more sanity check before that - right below the function header in `main.lua`
https://github.com/ggandor/leap.nvim/blob/c19e974cfd9d52dc5070ec7b68183da39702c877/lua/leap/main.lua#L394
insert:
```
exec_user_autocmds("LeapEnter")
```
so that we can really be sure no monkey business happens inside.

**Comment by curiousyogurt** [comment]
> One more sanity check before that - right below the function header in `main.lua` insert:
> ```lua
> exec_user_autocmds("LeapEnter")
> ```

As with @CharlieCheckpt, no message displaying "Leap is active".  Furthermore, no change in behaviour when modifying main.lua as suggested above.

Additionally, the script gets acknowledged in the list of scripts from :scriptnames.

**Comment by ggandor** [comment]
Try to call Leap manually: `:lua require('leap').leap {}`. Does it work?

**Comment by ggandor** [comment]
> :nmap s returns nothing

@donhcd had the same problem while having the Leap mappings intact though...

**Comment by curiousyogurt** [comment]
> 

Yes, this does work.

**Comment by curiousyogurt** [comment]
> Try to call Leap manually: :lua require('leap').leap {}. Does it work?

Yes, this does work.

**Comment by ggandor** [comment]
I cannot reproduce it anymore, but have you folks tried to update Neovim? Or test on stable vs nightly first?

**Comment by curiousyogurt** [comment]
@CharlieCheckpt No, this problem is not solved.  I can trigger Leap by calling in manually—but I have to do so each and every time I want to use it.

**Comment by curiousyogurt** [comment]
@ggandor I'm currently on version 0.8.1 of NeoVim, and that uses LuaJIT 2.1.0-beta.

**Comment by curiousyogurt** [comment]
When I added this to init.lua, Leap started to work just fine:

    require('leap').add_default_mappings()

I'm still quite puzzled about its working to begin with, then ceasing to work.  But this restores functionality.

**Comment by maxmahlke** [comment]
I just switched from `lightspeed` to `leap`. I added `use("ggandor/leap.nvim)` to my packer startup function and `require('leap').add_default_mappings()` at the very end of my `init.lua`. The keybinds do not work, though `nmap s` shows that they are registered. `nvim` version is `NVIM v0.9.0-dev-280+gfae754073`, I updated to `NVIM v0.9.0-dev-361+g126ef65e5` which did not solve the problem.

**Comment by Liampor** [comment]
> > Try to call Leap manually: :lua require('leap').leap {}. Does it work?
> 
> Yes, this does work: after entering this command, I can type two characters and leap works as expected.

I have exactly the same issue with WSL1 + Neovim 0.9dev

**Comment by liujoey** [comment]
Do you guys use any dashboard plugin?
What happens to me, is when calling the leap.add_default_mappings(), my dashboard plugin is active, and the dashboard plugin mapped `s` key to "restore persistence", and `g` key to the lazy_git, both in normal mode, so leap politely not want to overwrite these mappings. 
@ggandor

**Comment by ggandor** [comment]
And of cause, I use lazy loading for leap, with event = { "BufReadPost", "BufNew" }, so leap been loaded right after the dashboard buffer. Remove this lazy loading (or change it to something happen before dashboard), solved my problem.

Besides, lazy-loading Leap is totally unnecessary, the plugin does that internally. If you `require'leap'`, it is just [`init.fnl`](https://github.com/ggandor/leap.nvim/blob/main/fnl/leap/init.fnl), the "dispatcher" module. `main` is only loaded once you start a Leap motion.
