### ISSUE TITLE
Add user command when pressing s

### ISSUE THREAD

**Issue by defr0std** [ggandor/leap.nvim#73]
Thanks for the great plugin.

I would like to have an option to have a small visual indicator right after pressing s/S. For example - change the mode in the lualine to something like SEARCH.

There is a LeapEnter user command, but it fires after pressing the first search letter already. And I would like to have something directly after pressing s/S.

Would it make sense to add one more user command? LeapStart?

**Comment by ggandor** [comment]
I'm confused. `LeapEnter` _is_ the very first thing that happens when invoking `leap`.

https://github.com/ggandor/leap.nvim/blob/5d9ddc0c0fbd879928225f3275f9530ebb6ac09f/fnl/leap/main.fnl#L621

**Comment by defr0std** [comment]
Oh, sorry for the confusion. What happens then is probably that lualine UI is not updated when LeapEnter is triggered, but it does update after typing the first character. I made the wrong assumption, sorry.

**Comment by SanderNotenbaert** [comment]
@defr0std I'm trying to do the exact same thing in lualine, and encountering the exact same problem. Did you get around it?

**Comment by ggandor** [comment]
@SanderNotenbaert  Add `:redrawstatus!` to the end of your callback (just a shot in the dark)?

**Comment by mitchellwrosen** [comment]
or

```lua
(require "lualine").refresh({ place = { "statusline" } })
```

**Comment by SanderNotenbaert** [comment]
Thanks! `vim.cmd("redrawstatus!")` didn't work for me, but adding `require('lualine').refresh({ place = { 'statusline' } })` into the LeapEnter callback did the trick! For future reference: I did try adding in the lualine refresh before, but I think the combination of a statusline refresh with an inline function as a lualine component option worked.
