### ISSUE TITLE
equivalence classes

### ISSUE THREAD

**Issue by yashamon** [ggandor/leap.nvim#78]
,What is the syntax for equivalence classes? If I want a and b to be equivalent do I write {a,b} or
{"a","b"}  or what, nothing works for me.

**Comment by ggandor** [comment]
https://github.com/ggandor/leap.nvim/blob/c19e974cfd9d52dc5070ec7b68183da39702c877/doc/leap.txt#L152-L165

**Comment by yashamon** [comment]
I don't understand the example. Is an equivalence class represented by a standard list data structure? If so is  ')]}>', short hand for {')', ']', '}', '>'} , or what? (Not a programmer here.)

Eventually {'a', 'b'} syntax did work for me, I think there was a syntax error elsewhere before.

**Comment by ggandor** [comment]
> Is an equivalence class represented by a standard list data structure? If so is ')]}>', short hand for {')', ']', '}', '>'} , or what?

A list `{'a', 'b', 'c'}` is used internally, but you can also define it as a string `'abc'` in your config. This is just a convenience feature. In this latter case, we automatically convert the string to a list first.

**Comment by yashamon** [comment]
Thanks!
