### ISSUE TITLE
packer error

### ISSUE THREAD

**Issue by CRAG666** [ggandor/leap.nvim#8]
```lua
    use {
      "ggandor/leap.nvim",
      config = function()
        require("leap").set_default_keymaps()
      end,
    }
```
![screen-1649474699](https://user-images.githubusercontent.com/34254373/162554588-2ba63eaf-6db7-47a7-a2cb-bdf19103aaae.png)

**Comment by ggandor** [comment]
There was a breaking change, you need to update Neovim (see #7).

**Comment by CRAG666** [comment]
i am use neovim 7
