### ISSUE TITLE
Unable to setup <Plug>(leap-cross-window)

### ISSUE THREAD

**Issue by sabah1994** [ggandor/leap.nvim#80]
Hi, 
I haven't been able to setup bidirectional search. 

My config
require('leap')
vim.keymap.set({'n', 'x', 'o'}, 's', "<Plug>(leap-cross-window)")

Error I get when i try to use this mapping "no targetable windows" 

how do I set up bidirectional search?

**Comment by ggandor** [comment]
See FAQ. On the right hand side you should use `function () require('leap').leap { target_windows = { vim.fn.win_getid() } } end`.  There is no predefined `<Plug>` key for bidirectional search in the current window (`<Plug>(leap-cross-window)` jumps to the _other_ windows on the tab page).

P.S.: No need to `require('leap')` if you don't want to set something in the `opts` table.

**Comment by sabah1994** [comment]
Thank you
