### ISSUE TITLE
VSCode-Neovim with leap.nvim buffer sync issue (and workaround)

### ISSUE THREAD

**Issue by ctstacey** [ggandor/leap.nvim#82]
This issue is not within the scope of leap.nvim to investigate/fix
I am providing this workaround here for the benefit of other leap.nvim users.

16 Dec 2022

- Windows 10 Pro 21H2 19044.2251 64-bit
- VSCode 1.74.1
- Neovim 0.8.0
  https://neovim.io/
- VSCode Neovim 0.0.95
  https://marketplace.visualstudio.com/items?itemName=asvetliakov.vscode-neovim
- leap.nvim
  (successor to lightspeed.nvim)
  https://github.com/ggandor/leap.nvim

This demonstration shows a minor flaw in the syncing between the displayed lines on the VSCode screen (tab) and the 'visual area/screen' in the buffer of the Neovim headless backend.

ISSUE:
When VSCode opens, it takes you to the last tab you had open, and positions your cursor where you left it when VSCode was shut down.
However, when you try to leap backward (using leap.nvim), the search results only extend a dozen or so lines above the cursor.
My best guess, is the text that displays in VSCode, is not matching what's loaded into the 'visible area/screen' in the buffer of the headless Neovim instance.

When you move up the file past the dozen or so lines that are being searched, you can move up the file line by line trying a new backward leap each time. Each time the result is the same. The top of the searched area is limited to the line the cursor is on. At each step the highest line becomes the new boundary for search results of the backward leap. You can move down the file again and the boundary stays in the same position.

WORKAROUND:
The workaround is to move the cursor to the first line of the file, then move it back to where you started. You can do this manually, or by script (as is shown here).

Hope this helps,
Happy Developing!
Chris Stacey

```vim
" -------------------------------
" init.vim
" chris stacey 2022
" -------------------------------
" leap.nvim
" successor to lightspeed.nvim
" https://github.com/ggandor/leap.nvim
" depends on repeat.vim (if you want . to repeat leaps)
"   https://github.com/tpope/vim-repeat

lua require('leap').add_default_mappings()

" Forces VSCode and the headless nvim in the back, to sync properly.
" Needed so the ggandor/leap.nvim plugin can leap backward correctly.
"
" When you close VSCode, it remembers your last file, and cursor position.
" When you re-open VSCode, it starts you back in the same spot.
" However, it seems it starts slightly out of sync with the headless nvim in the back.
" There appear to be less lines loaded into the (headless) nvim's visible screen area,
" than are visible in the VSCode screen.
" This causes the ggandor/leap.nvim plugin to not be able to search the entire visible
" screen area shown in VSCode.
" Navigating upward to the top of the visible area fixes this issue (they sync).
" However, I found simply using H to move to the top of the screen was insufficient.
" Moving to the top of the file fixes the sync, thus it fixes leaping backward in leap.

function s:resync_vscode_and_nvim_buffer()
  if exists('b:resync_vscode_and_nvim_buffer_completed')
    " pass
  else
    echo "syncing VSCode screen (tab) with Nvim buffer so ggandor/leap.nvim is able to leap backward correctly"
    let l:lnum = line(".")
    execute "keepjumps keeppatterns normal! gg"
    execute "keepjumps keeppatterns normal! " .. l:lnum .. "gg"
    let b:resync_vscode_and_nvim_buffer_completed = 1
  endif
endfunction

nnoremap S :call <SID>resync_vscode_and_nvim_buffer()<Cr><Plug>(leap-backward-to)
```

demo .gif (video) - 20s pause at start
![leap-neovim-vid11](https://user-images.githubusercontent.com/51082452/207927524-0393adf4-a775-4b67-b8a6-2ff7c37e1809.gif)

**Comment by ggandor** [comment]
> This issue is not within the scope of leap.nvim to investigate/fix
> I am providing this workaround here for the benefit of other leap.nvim users.

You should open an issue in [vscode-neovim](https://github.com/vscode-neovim/vscode-neovim) though, since this is a bug to be fixed.

**Comment by ctstacey** [comment]
Will do, thanks 👍
