### ISSUE TITLE
Is there a way to always place cursor on the first match?

### ISSUE THREAD

**Issue by snacksncode** [ggandor/leap.nvim#84]
## Hi :wave: 
Is it possible to always place cursor on the first match even if there are other matches?
I've attached minimal showcase of what I mean.

https://user-images.githubusercontent.com/50829382/208455989-a8c342c7-4555-4b6f-b4cc-c726f88ebf2a.mp4

When there's 2 `null`s in the viewport there's 2 matches after `snu` and the cursor is actually places on that first match. It's just not very apparent as it's only visible after a movement command.

But when there's no other matches in the viewport for `snu` cursor is placed on that first match without the need for movement command.

I think this all has something to do with "Smart autojump" but I'm not sure.

**Comment by ctstacey** [comment]
If I understand your issue correctly, you need to define the Cursor colour in nvim. See issue #27.

**Comment by ggandor** [comment]
> If I understand your issue correctly, you need to define the Cursor colour in nvim. See issue https://github.com/ggandor/leap.nvim/issues/27.

Yep. See also #70.
