### ISSUE TITLE
when in visual mode, lowercase x doesn't work anymore

### ISSUE THREAD

**Issue by lucax88x** [ggandor/leap.nvim#88]
I noticed this plugin, when add_default_mappings is called makes lower case x not work when in visual mode

uppercase X in visual mode works fine, and also lowercase x in normal mode works fine.

**Comment by ggandor** [comment]
You (or one of your plugins) have probably mapped `x` to something in visual mode (check with `map x`). You can also try `add_default_mappings(true)`.
