### ISSUE TITLE
needs to be ignore in select-mode

### ISSUE THREAD

**Issue by abenz1267** [ggandor/leap.nvim#9]
Hi,

i noticed that in select-mode leap also works, without intention! It really shouldn't work in select-mode i think.

Regards

**Comment by ggandor** [comment]
I cannot reproduce, Leap uses `x` when doing the mappings. Do you use the default keymaps, or have you set custom ones?

**Comment by abenz1267** [comment]
Indeed i have mapped leap-forward to normal-mode f.

**Comment by ggandor** [comment]
And the editor is _actually_ in select mode, i.e., on the command line you see `-- SELECT --`? I think this issue has something to do with nvim-cmp, maybe it would worth asking about it in their repo.  I vaguely remember some similar (or maybe the same?) issue raised by someone in the Lightspeed repo, and the conclusion was the same, it's not about the motion plugin. It would be good to check first if Sneak or Lightspeed behaves the same way (most probably they do).

**Comment by abenz1267** [comment]
Yeah, it's definitely in select mode. Otherwise i wouldn't have know tbh.

**Comment by ggandor** [comment]
> Noticed i had a visual mode binding as well i actually didn't use. so removed it for now.

You can use `x[map]` instead of `v[map]` instead, that's the "visual-excluding-select" mode.

**Comment by danieleavitabile** [comment]
Sorry if what I write below is unrelated (I'm a newbie with this plugin, and not overly expert with nevoim). When leap is inactive I can do the following: 

1. Use ctrl-v to enter in the Visual Block mode
2. Move around to select an area
3. Press x to delete it

When I activate leap and set:

` lua require('leap').add_default_mappings()`

Then steps 1 and 2 work well, but 3 does not delete anything. Is this an intended leap behaviour?

**Comment by harrisoncramer** [comment]
Sorry to revive this, but how can one turn on the default mappings _except_ for those in select mode? I'm often using `x` in visual mode to remove text in a blockwise selection and don't want to use leap here...

**Comment by ggandor** [comment]
@harrisoncramer To make sure we're on the same page: you mean _select_ mode (`:h Select-mode`), or just Visual? Leap doesn't define mappings in Select mode, it uses `x` (Visual excluding Select). If you're question is simply about removing `x`/`X` in Visual mode, then, well, remove them after calling `add_default_mappings`. (`vim.keymap.del('x', 'x')` + `vim.keymap.del('x', 'X')`, or, in much shorter vimscript-style: `xunmap x | xunmap X`.)

**Comment by harrisoncramer** [comment]
Ah yes, apologies, was referring to visual mode. Awesome! Thanks.
