### ISSUE TITLE
module 'leap' not found

### ISSUE THREAD

**Issue by Lengdrich** [ggandor/leap.nvim#94]
I use `leap.nvim` install the `leap.nvim` plugin. Every time I open the nvim, this error message will pop up
I use the `wsl2` and my neovim version is `0.8.2`.
this is the error message:
```
Failed to run `config` for leap.nvim

/home/ethan/.config/nvim/lua/modules/editor/package.lua:32: module 'leap' not found:
^Ino field package.preload['leap']module leap not found
^Ino file './leap.lua'
^Ino file '/home/runner/work/neovim/neovim/.deps/usr/share/luajit-2.1.0-beta3/leap.lua'
^Ino file '/usr/local/share/lua/5.1/leap.lua'
^Ino file '/usr/local/share/lua/5.1/leap/init.lua'
^Ino file '/home/runner/work/neovim/neovim/.deps/usr/share/lua/5.1/leap.lua'
^Ino file '/home/runner/work/neovim/neovim/.deps/usr/share/lua/5.1/leap/init.lua'
^Ino file './leap.so'
^Ino file '/usr/local/lib/lua/5.1/leap.so'
^Ino file '/home/runner/work/neovim/neovim/.deps/usr/lib/lua/5.1/leap.so'
^Ino file '/usr/local/lib/lua/5.1/loadall.so'

# stacktrace:
Press ENTER or type command to continue
  - lua/modules/editor/package.lua:32 _in_ **config**
Press ENTER or type command to continue
Client 1 quit with exit code 1 and signal 0
Press ENTER or type command to continue
```

And this is my config with lazy.nvim
```lua
package({
  'ggandor/leap.nvim',
  event = 'BufRead',
  dependencies = {
    'tpope/vim-repeat',
  },
  config = function()
    require('leap').add_default_mappings()
  end
})
```

**Comment by Lengdrich** [comment]
the `package.lua:32` is the `require('leap').add_default_mappings()`

**Comment by Lengdrich** [comment]
And, Every time I enter `:h leap-config`, nvim will display `no help for leap-config`. But lazy.nvim shows that I have installed `leap.nvim`

**Comment by ggandor** [comment]
Sorry, but I have no idea, this is a package management issue, ask folke.

**Comment by folke** [comment]
@Lengdrich feel free to post an issue on lazy with a minimal repro. Not a leap issue indeed. Not sure what your `package()` function does...

That docs thing is standard Neovim behavior. Docs only show when a plugin is loaded

**Comment by Lengdrich** [comment]
> Sorry, but I have no idea, this is a package management issue, ask @folke.

Sorry，I have solved this problem. When I installed leap.nvim, lazy.nvim only installed an empty folder without any content(I think it should be caused by the network). I deleted this folder and reinstalled it. The problem was solved.

**Comment by Lengdrich** [comment]
> @Lengdrich feel free to post an issue on lazy with a minimal repro. Not a leap issue indeed. Not sure what your `package()` function does...
> 
> That docs thing is standard Neovim behavior. Docs only show when a plugin is loaded

Sorry，I have solved this problem. When I installed leap.nvim, lazy.nvim only installed an empty folder without any content(I think it should be caused by the network). I deleted this folder and reinstalled it. The problem was solved.
