### ISSUE TITLE
[bug]after install leap.nvim fails to enter the session directly

### ISSUE THREAD

**Issue by liaohui5** [ggandor/leap.nvim#95]
## problem

When `leap.nvim` not installed, `vim.opt.shortmess:append({ s = true, I = true })` is working

When `leap.nvim` is installed, `vim.opt.shortmess:append({ s= true, I = true })` does not working

I wanted to go straight to session, but every time I opened neovim, 
a blank page appeared and I had to press a key to get to session

## env
os: macos 13.1
neovim: 0.8.2
session manage plugin:  https://github.com/Shatur/neovim-session-manager

## config
```
require("leap").leap({
  target_windows = {
    vim.fn.win_getid(),
  }
});

vim.api.nvim_set_hl(0, "LeapBackdrop", {
  link = "Comment",
});
vim.api.nvim_set_hl(0, "LeapMatch", {
  fg = "white",
  bold = false,
  nocombine = true,
});
leap.add_default_mappings();
```

**Comment by ggandor** [comment]
First of all,
```
require("leap").leap({ target_windows = { vim.fn.win_getid() }})
```
should be wrapped in a function and mapped to a key, it's a call of the jump function itself. If you put this into your config, Leap will be called every time you open Neovim.

**Comment by liaohui5** [comment]
> First of all,
> 
> ```
> require("leap").leap({ target_windows = { vim.fn.win_getid() }})
> ```
> 
> is a call to the jump function itself, if you put the above into your config, Leap will be called every time you open Neovim. That line should be wrapped in a function and mapped to some key (`vim.keymap.set({'n', 'x'}, <some-key>, function () require('leap').leap { ... } end)`).


Ok, I see. Thank you very much 👍, my problem solved.
I thought 'leap.leap' was the setup function of leap.nvim
